// Journaux VERA (donnees statiques)
export const JOURNAUX_VERA = [
    {
        id: 'journal_1',
        numero: 1,
        titre: 'TRANSMISSION 01',
        sousTitre: 'Inferno — Jour inconnu',
        biomeId: 'lave',
        condition: 'effacer_10_lignes_biome',
        texte: [
            "Je l'ai trouve. La source.",
            "Elle n'est pas où je croyais.",
            "Ce n'est pas une anomalie technique.",
            "C'est quelque chose qui souffre.",
        ],
        illustration: 'dessinerJournalVera1',
    },
    {
        id: 'journal_2',
        numero: 2,
        titre: 'TRANSMISSION 02',
        sousTitre: 'La Rouille — Atelier abandonne',
        biomeId: 'rouille',
        condition: 'effacer_8_lignes_biome',
        texte: [
            "Ces machines n'auraient pas dû continuer de fonctionner.",
            'Et pourtant. Elles produisent des pieces.',
            'Des pieces que personne ne commande.',
            "Comme si elles attendaient quelqu'un.",
        ],
        illustration: 'dessinerJournalVera2',
    },
    {
        id: 'journal_3',
        numero: 3,
        titre: 'TRANSMISSION 03',
        sousTitre: 'Abysses — Profondeur 400m',
        biomeId: 'ocean',
        condition: 'effacer_10_lignes_biome',
        texte: [
            "Elle m'a repondu.",
            "Je n'ai pas compris sa langue.",
            "Mais j'ai compris sa douleur.",
            "Elle n'attaque pas. Elle se defend.",
        ],
        illustration: 'dessinerJournalVera3',
    },
    {
        id: 'journal_4',
        numero: 4,
        titre: 'TRANSMISSION 04',
        sousTitre: 'La Canopee — Quelque part en hauteur',
        biomeId: 'foret',
        condition: 'effacer_10_lignes_biome',
        texte: [
            "Elle m'a montre sa forme reelle.",
            'Pas un monstre. Une accumulation.',
            'Des millions de frustrations, cristallisees.',
            "Qui d'entre nous aurait resiste ?",
        ],
        illustration: 'dessinerJournalVera4',
    },
    {
        id: 'journal_5',
        numero: 5,
        titre: 'TRANSMISSION 05',
        sousTitre: 'Arctique — Apres la Sentinelle',
        biomeId: 'glace',
        condition: 'debloquer_apres_boss_sentinelle',
        texte: [
            "J'ai une theorie.",
            'Si completer des lignes renforce la Trame,',
            "alors laisser une ligne incomplete l'affaiblit.",
            "La Distorsion n'est pas nee d'une erreur. Elle est nee d'un choix.",
        ],
        illustration: 'dessinerJournalVera5',
    },
    {
        id: 'journal_6',
        numero: 6,
        titre: 'TRANSMISSION 06',
        sousTitre: 'Le Desert — Incomplet',
        biomeId: 'desert',
        condition: 'effacer_10_lignes_biome',
        texte: [],
        illustration: 'dessinerJournalVera6',
        estEndommage: true,
    },
    {
        id: 'journal_7',
        numero: 7,
        titre: 'TRANSMISSION 07',
        sousTitre: 'CYBER — Laboratoire de VERA',
        biomeId: 'cyber',
        condition: 'trouver_laboratoire_vera',
        texte: [
            'Robo.',
            "Si tu lis ceci, c'est que tu es arrive jusqu'ici.",
            'Je suis fiere de toi. Je ne pensais pas que tu en serais capable.',
            "Maintenant : je vais entrer dans la Trame. Ne m'attends pas.",
        ],
        illustration: 'dessinerJournalVera7',
        estMessageDirect: true,
    },
    {
        id: 'journal_8',
        numero: 8,
        titre: 'TRANSMISSION 08',
        sousTitre: 'Cosmos — Bord de la Trame',
        biomeId: 'cosmos',
        condition: 'effacer_12_lignes_biome',
        texte: [
            'Robo. Si tu trouves ceci,',
            "c'est que je n'ai pas reussi à revenir.",
            "Mais j'ai laisse quelque chose dans la Trame.",
            'Une ligne. Incomplete. Expres.',
        ],
        illustration: 'dessinerJournalVera8',
    },
    {
        id: 'journal_9',
        numero: 9,
        titre: 'TRANSMISSION 09',
        sousTitre: 'Le Vide — Dernier signal',
        biomeId: 'vide',
        condition: 'effacer_8_lignes_biome',
        texte: [
            "La ligne incomplete que j'ai laissee —",
            "c'est une porte.",
            'Pour y entrer, tu dois faire ce qui te coûte le plus :',
            'laisser quelque chose inacheve.',
        ],
        illustration: 'dessinerJournalVera9',
    },
];
