// Donnees narratives — personnages et boss
// Donnees narratives du Mode Histoire — "La Fragmentation"

export const PERSONNAGES = {
    robo: {
        id: 'robo',
        nom: 'ROBO',
        description: 'Gardien de la Trame. Construit en urgence par VERA.',
    },
    vera: {
        id: 'vera',
        nom: 'VERA',
        titreLong: 'Vectorielle Experte en Realite Architecturee',
        description: 'Creatrice de Robo. Piegee dans la Trame Primordiale.',
    },
    distorsion: {
        id: 'distorsion',
        nom: 'LA DISTORSION',
        description: "Nee de l'accumulation de millions de lignes incompletes.",
    },
};

export const BOSS = {
    brasier: {
        id: 'brasier',
        nom: 'LE BRASIER PERPÉTUEL',
        icone: '🔥',
        biomeId: 'lave',
        couleur: '#ff4500',
        pvMax: 14,
        attaqueIntervalleMs: 22000,
        attaqueType: 'rangee_braise',
        portrait: 'drawBossPortraitBrasier',
        texteApparition: 'Je suis tout ce que vous avez laisse brûler.',
        texteDefaite: 'Vous... completez... tout.',
    },
    sentinelle: {
        id: 'sentinelle',
        nom: 'LA SENTINELLE DES GLACES',
        icone: '❄️',
        biomeId: 'glace',
        couleur: '#aaeeff',
        pvMax: 12,
        attaqueIntervalleMs: 19000,
        attaqueType: 'colonne_gelee',
        nbColonnesGelees: 2,
        dureeGelee: 8000,
        portrait: 'drawBossPortraitSentinelle',
        texteApparition: 'Arrêtez. Arrêtez tout. Le gel preserve.',
        texteDefaite: 'Le temps... ne peut pas... tout arrêter.',
    },
    archiviste: {
        id: 'archiviste',
        nom: "L'ARCHIVISTE CORROMPU",
        icone: '⚠',
        biomeId: 'cyber',
        couleur: '#ff00ff',
        pvMax: 14,
        attaqueIntervalleMs: 15000,
        attaqueType: 'multi_phase',
        phases: [
            { pvSeuil: 13, type: 'inverser_controles', dureeMs: 6000 },
            { pvSeuil: 7, type: 'faux_fantome', dureeMs: 8000 },
        ],
        portrait: 'drawBossPortraitArchiviste',
        texteApparition: 'Les archives ne mentent pas. Toi, si.',
        texteDefaite: 'Erreur_404: logique_introuvable.',
    },
    avantgarde: {
        id: 'avantgarde',
        nom: "L'AVANT-GARDE",
        icone: '🌀',
        biomeId: 'cosmos',
        couleur: '#7700ff',
        entrainement: true,
        pvMax: 10,
        attaqueIntervalleMs: 16000,
        attaqueType: 'combinaison',
        attaquesDisponibles: ['permutation_colonnes', 'permutation_colonnes', 'colonne_gelee'],
        portrait: 'drawBossPortraitAvantgarde',
        texteApparition: 'La Distorsion vous attend. Je vous prepare.',
        texteDefaite: 'Vous... êtes prêt. Elle... aussi.',
    },
    distorsion: {
        id: 'distorsion',
        nom: 'LA DISTORSION',
        icone: '∞',
        biomeId: 'cosmos',
        couleur: '#ff006e',
        pvMax: 32,
        attaqueIntervalleMs: 13000,
        attaqueType: 'rangee_braise',
        phases: [
            { pvSeuil: 32, attaqueType: 'rangee_braise' },
            { pvSeuil: 24, attaqueType: 'combinaison_glace_glitch' },
            { pvSeuil: 12, attaqueType: 'distorsion_plateau' },
        ],
        portrait: 'drawBossPortraitDistorsion',
        texteApparition: "Enfin. Tu comprends, n'est-ce pas ? Tout cela est inutile.",
        texteDefaite: "J'ai... perdu... cette fois.",
        texteDefaite_normal: "J'ai... perdu... cette fois.",
        texteDefaite_vrai: "Tu m'as... completee.",
        texteDefaite_secret: 'VERA... dit bonjour.',
    },
};
