/** @typedef {{ id: string, nom: string, biome: string, difficulte: 1|2|3, parPieces: number, silhouette: string[], pieces: { type: string, qte: number }[], deblocage: number }} NiveauArchi */

/** @type {NiveauArchi[]} */
export const NIVEAUX_ARCHI = [
    {
        id: 'carre_classique',
        nom: 'LE CARRÉ',
        biome: 'classique',
        difficulte: 1,
        parPieces: 4,
        deblocage: 0,
        silhouette: ['....####..', '....####..', '....####..', '....####..'],
        pieces: [{ type: 'O', qte: 4 }],
    },
    {
        id: 'croix_classique',
        nom: 'LA CROIX',
        biome: 'classique',
        difficulte: 1,
        parPieces: 3,
        deblocage: 0,
        silhouette: ['....##....', '....##....', '..######..', '....##....', '....##....'],
        pieces: [
            { type: 'I', qte: 2 },
            { type: 'T', qte: 2 },
        ],
    },
    {
        id: 'coeur_classique',
        nom: 'LE CŒUR',
        biome: 'classique',
        difficulte: 2,
        parPieces: 5,
        deblocage: 400,
        silhouette: [
            '.###.###..',
            '.########.',
            '.########.',
            '..######..',
            '...####...',
            '....##....',
        ],
        pieces: [
            { type: 'O', qte: 2 },
            { type: 'S', qte: 2 },
            { type: 'Z', qte: 2 },
            { type: 'T', qte: 2 },
        ],
    },
    {
        id: 'flamme_lave',
        nom: 'LA FLAMME',
        biome: 'lave',
        difficulte: 2,
        parPieces: 4,
        deblocage: 500,
        silhouette: [
            '....##....',
            '...####...',
            '..######..',
            '..######..',
            '...####...',
            '....##....',
            '....##....',
        ],
        pieces: [
            { type: 'I', qte: 2 },
            { type: 'T', qte: 3 },
            { type: 'S', qte: 1 },
            { type: 'Z', qte: 1 },
        ],
    },
    {
        id: 'volcan_lave',
        nom: 'LE VOLCAN',
        biome: 'lave',
        difficulte: 3,
        parPieces: 6,
        deblocage: 700,
        silhouette: [
            '....##....',
            '...####...',
            '..######..',
            '.########.',
            '####..####',
            '##......##',
        ],
        pieces: [
            { type: 'I', qte: 2 },
            { type: 'L', qte: 2 },
            { type: 'J', qte: 2 },
            { type: 'T', qte: 2 },
            { type: 'O', qte: 1 },
        ],
    },
    {
        id: 'vague_ocean',
        nom: 'LA VAGUE',
        biome: 'ocean',
        difficulte: 2,
        parPieces: 5,
        deblocage: 600,
        silhouette: ['##......##', '###....###', '.###..###.', '..######..', '...####...'],
        pieces: [
            { type: 'S', qte: 2 },
            { type: 'Z', qte: 2 },
            { type: 'J', qte: 2 },
            { type: 'L', qte: 2 },
        ],
    },
    {
        id: 'poisson_ocean',
        nom: 'LE POISSON',
        biome: 'ocean',
        difficulte: 3,
        parPieces: 7,
        deblocage: 800,
        silhouette: ['##..###...', '##.#####..', '##.######.', '##.#####..', '##..###...'],
        pieces: [
            { type: 'O', qte: 3 },
            { type: 'L', qte: 2 },
            { type: 'J', qte: 2 },
            { type: 'I', qte: 1 },
        ],
    },
    {
        id: 'arbre_foret',
        nom: "L'ARBRE",
        biome: 'foret',
        difficulte: 2,
        parPieces: 5,
        deblocage: 700,
        silhouette: [
            '....##....',
            '...####...',
            '..######..',
            '.########.',
            '....##....',
            '....##....',
        ],
        pieces: [
            { type: 'T', qte: 3 },
            { type: 'I', qte: 1 },
            { type: 'L', qte: 2 },
            { type: 'J', qte: 2 },
        ],
    },
    {
        id: 'feuille_foret',
        nom: 'LA FEUILLE',
        biome: 'foret',
        difficulte: 3,
        parPieces: 6,
        deblocage: 900,
        silhouette: [
            '.....#....',
            '....###...',
            '...#####..',
            '..#######.',
            '...#####..',
            '....###...',
            '....##....',
        ],
        pieces: [
            { type: 'S', qte: 2 },
            { type: 'Z', qte: 2 },
            { type: 'T', qte: 3 },
            { type: 'I', qte: 2 },
        ],
    },
    {
        id: 'flocon_glace',
        nom: 'LE FLOCON',
        biome: 'glace',
        difficulte: 3,
        parPieces: 6,
        deblocage: 1000,
        silhouette: [
            '....##....',
            '.##.##.##.',
            '..######..',
            '..######..',
            '.##.##.##.',
            '....##....',
        ],
        pieces: [
            { type: 'I', qte: 2 },
            { type: 'O', qte: 2 },
            { type: 'T', qte: 2 },
            { type: 'S', qte: 1 },
            { type: 'Z', qte: 1 },
        ],
    },
    {
        id: 'pyramide_desert',
        nom: 'LA PYRAMIDE',
        biome: 'desert',
        difficulte: 2,
        parPieces: 5,
        deblocage: 800,
        silhouette: ['....##....', '...####...', '..######..', '.########.', '##########'],
        pieces: [
            { type: 'I', qte: 2 },
            { type: 'T', qte: 2 },
            { type: 'L', qte: 2 },
            { type: 'J', qte: 2 },
            { type: 'O', qte: 1 },
        ],
    },
    {
        id: 'dune_desert',
        nom: 'LA DUNE',
        biome: 'desert',
        difficulte: 3,
        parPieces: 7,
        deblocage: 1100,
        silhouette: [
            '.....#....',
            '....###...',
            '...######.',
            '..########',
            '.#########',
            '##########',
        ],
        pieces: [
            { type: 'L', qte: 3 },
            { type: 'J', qte: 3 },
            { type: 'S', qte: 2 },
            { type: 'Z', qte: 2 },
        ],
    },
    {
        id: 'eclair_cyber',
        nom: "L'ÉCLAIR",
        biome: 'cyber',
        difficulte: 2,
        parPieces: 4,
        deblocage: 900,
        silhouette: [
            '...####...',
            '....####..',
            '.....##...',
            '....####..',
            '...####...',
            '..####....',
        ],
        pieces: [
            { type: 'S', qte: 3 },
            { type: 'Z', qte: 3 },
            { type: 'T', qte: 2 },
        ],
    },
    {
        id: 'robot_cyber',
        nom: 'LE ROBOT',
        biome: 'cyber',
        difficulte: 3,
        parPieces: 8,
        deblocage: 1200,
        silhouette: [
            '..######..',
            '..######..',
            '..##..##..',
            '..######..',
            '...####...',
            '..######..',
            '..##..##..',
            '..##..##..',
        ],
        pieces: [
            { type: 'O', qte: 4 },
            { type: 'I', qte: 2 },
            { type: 'T', qte: 2 },
            { type: 'L', qte: 1 },
            { type: 'J', qte: 1 },
        ],
    },
    {
        id: 'etoile_fuochi',
        nom: "L'ÉTOILE",
        biome: 'fuochi',
        difficulte: 3,
        parPieces: 6,
        deblocage: 1000,
        silhouette: [
            '....##....',
            '.##.##.##.',
            '..######..',
            '##########',
            '..######..',
            '.##.##.##.',
            '....##....',
        ],
        pieces: [
            { type: 'I', qte: 3 },
            { type: 'O', qte: 2 },
            { type: 'T', qte: 3 },
            { type: 'S', qte: 1 },
            { type: 'Z', qte: 1 },
        ],
    },
    {
        id: 'fusee_cosmos',
        nom: 'LA FUSÉE',
        biome: 'cosmos',
        difficulte: 3,
        parPieces: 7,
        deblocage: 1300,
        silhouette: [
            '....##....',
            '...####...',
            '...####...',
            '...####...',
            '...####...',
            '..######..',
            '.########.',
            '...####...',
            '..##..##..',
        ],
        pieces: [
            { type: 'I', qte: 2 },
            { type: 'O', qte: 3 },
            { type: 'T', qte: 2 },
            { type: 'L', qte: 2 },
            { type: 'J', qte: 2 },
        ],
    },
    {
        id: 'lune_cosmos',
        nom: 'LA LUNE',
        biome: 'cosmos',
        difficulte: 3,
        parPieces: 6,
        deblocage: 1500,
        silhouette: [
            '..####....',
            '.######...',
            '########..',
            '########..',
            '.######...',
            '..####....',
        ],
        pieces: [
            { type: 'O', qte: 3 },
            { type: 'L', qte: 2 },
            { type: 'J', qte: 2 },
            { type: 'S', qte: 1 },
            { type: 'Z', qte: 1 },
        ],
    },
];
