export const CONFIG = {
    colonnes: 10,
    lignes: 20,
    taille: 32,
    vitesseBase: 900,
    vitesseMin: 80,
    reductionParNiveau: 60,
    lockDelay: 500,
    maxLockResets: 15,
    dasDelai: 167,
    arrInterval: 33,
    sprintLignes: 40,
};

const UI_CLASSIQUE = {
    bordureCanvas: '#00f5ff',
    couleurPrimaire: '#00f5ff',
    couleurScore: '#ffe600',
    couleurAccent: '#00f5ff',
    fondPanneau: 'rgba(0,245,255,0.04)',
    bordurePanneau: 'rgba(0,245,255,0.2)',
};

const TEXTES_CLASSIQUE = {
    score: 'SCORE',
    lignes: 'LIGNES',
    niveau: 'NIVEAU',
    hold: 'RÉSERVE',
    next: 'SUIVANT',
    gameOver: 'GAME OVER',
    pause: 'PAUSE',
    robo: 'ROBO',
    record: 'RECORD',
};

export const BIOMES = {
    classique: {
        id: 'classique',
        nom: 'CLASSIQUE',
        icone: '🎮',
        niveauDeblocage: 0,
        couleursBlocs: [
            '#00f5ff',
            '#ffe600',
            '#b400ff',
            '#00ff88',
            '#ff006e',
            '#4488ff',
            '#ff8800',
        ],
        fondCiel: '#08081a',
        fondSol: '#0c0c28',
        grilleCoul: 'rgba(0,245,255,0.04)',
        lueurCoul: '#00f5ff',
        styleBloc: 'biseaute',
        ui: UI_CLASSIQUE,
        textes: TEXTES_CLASSIQUE,
        musique: { tempo: 130, gamme: 'dorien', timbre: 'square', basse: true },
    },
    lave: {
        id: 'lave',
        nom: 'INFERNO',
        icone: '🌋',
        niveauDeblocage: 3,
        couleursBlocs: [
            '#ff4500',
            '#ff6a00',
            '#ff8c00',
            '#ffb700',
            '#cc1f00',
            '#e03000',
            '#ffdd00',
        ],
        fondCiel: '#1a0400',
        fondSol: '#2d0800',
        grilleCoul: 'rgba(255,80,0,0.05)',
        lueurCoul: '#ff4500',
        styleBloc: 'fondu',
        ui: {
            bordureCanvas: '#ff4500',
            couleurPrimaire: '#ff6a00',
            couleurScore: '#ffb700',
            couleurAccent: '#ff4500',
            fondPanneau: 'rgba(255,69,0,0.06)',
            bordurePanneau: 'rgba(255,80,0,0.25)',
        },
        textes: {
            score: 'CHALEUR',
            lignes: 'ÉRUPTIONS',
            niveau: 'STRATE',
            hold: 'MAGMA',
            next: 'FUSION',
            gameOver: 'FONDU !',
            pause: 'REFROIDI',
            robo: 'PYRO',
            record: 'TEMPÉRATURE MAX',
        },
        musique: { tempo: 100, gamme: 'phrygien', timbre: 'sawtooth', basse: true },
    },
    ocean: {
        id: 'ocean',
        nom: 'ABYSSES',
        icone: '🌊',
        niveauDeblocage: 6,
        couleursBlocs: [
            '#00cfff',
            '#0070dd',
            '#00aaff',
            '#00ffcc',
            '#0040cc',
            '#00e5ff',
            '#0099bb',
        ],
        fondCiel: '#000d1a',
        fondSol: '#001a33',
        grilleCoul: 'rgba(0,180,255,0.04)',
        lueurCoul: '#00cfff',
        styleBloc: 'cristal',
        ui: {
            bordureCanvas: '#00cfff',
            couleurPrimaire: '#00aaff',
            couleurScore: '#00ffcc',
            couleurAccent: '#0099ff',
            fondPanneau: 'rgba(0,180,255,0.05)',
            bordurePanneau: 'rgba(0,180,255,0.2)',
        },
        textes: {
            score: 'PRESSION',
            lignes: 'VAGUES',
            niveau: 'ABYSSES',
            hold: 'BULLE',
            next: 'COURANT',
            gameOver: 'NAUFRAGE',
            pause: 'MARÉE',
            robo: 'SOUS-MARIN',
            record: 'PLONGÉE MAX',
        },
        musique: { tempo: 90, gamme: 'pentatonique', timbre: 'sine', basse: false },
    },
    foret: {
        id: 'foret',
        nom: 'FORÊT',
        icone: '🌿',
        niveauDeblocage: 9,
        couleursBlocs: [
            '#00cc44',
            '#55dd00',
            '#88ff00',
            '#ffdd00',
            '#00aa22',
            '#66bb00',
            '#aaee44',
        ],
        fondCiel: '#020f02',
        fondSol: '#041804',
        grilleCoul: 'rgba(0,200,50,0.04)',
        lueurCoul: '#00cc44',
        styleBloc: 'organique',
        ui: {
            bordureCanvas: '#00cc44',
            couleurPrimaire: '#55dd00',
            couleurScore: '#aaee44',
            couleurAccent: '#00cc44',
            fondPanneau: 'rgba(0,200,50,0.05)',
            bordurePanneau: 'rgba(0,200,50,0.2)',
        },
        textes: {
            score: 'RACINES',
            lignes: 'BRANCHES',
            niveau: 'CANOPÉE',
            hold: 'GRAINE',
            next: 'POUSSE',
            gameOver: 'ABATTU',
            pause: 'HIBERNATION',
            robo: 'SYLV',
            record: 'FORÊT DENSE',
        },
        musique: { tempo: 110, gamme: 'majeur', timbre: 'triangle', basse: false },
    },
    glace: {
        id: 'glace',
        nom: 'ARCTIQUE',
        icone: '❄️',
        niveauDeblocage: 12,
        couleursBlocs: [
            '#aaeeff',
            '#cceeff',
            '#88ddff',
            '#ffffff',
            '#66ccff',
            '#aaddff',
            '#ddf4ff',
        ],
        fondCiel: '#030d14',
        fondSol: '#061828',
        grilleCoul: 'rgba(180,220,255,0.05)',
        lueurCoul: '#aaeeff',
        styleBloc: 'glace',
        ui: {
            bordureCanvas: '#aaeeff',
            couleurPrimaire: '#cceeff',
            couleurScore: '#ffffff',
            couleurAccent: '#88ddff',
            fondPanneau: 'rgba(180,230,255,0.05)',
            bordurePanneau: 'rgba(180,230,255,0.2)',
        },
        textes: {
            score: 'CRISTAUX',
            lignes: 'PLAQUES',
            niveau: 'GIVRE',
            hold: 'CONGÈLE',
            next: 'BANQUISE',
            gameOver: 'BRISÉ',
            pause: 'GELÉ',
            robo: 'FROST',
            record: 'ARCTIQUE MAX',
        },
        musique: { tempo: 80, gamme: 'lydien', timbre: 'sine', basse: false },
    },
    desert: {
        id: 'desert',
        nom: 'DÉSERT',
        icone: '🏜️',
        niveauDeblocage: 15,
        couleursBlocs: [
            '#ffbb44',
            '#ffaa00',
            '#dd8800',
            '#ff9922',
            '#cc7700',
            '#ffcc66',
            '#ffdd88',
        ],
        fondCiel: '#140800',
        fondSol: '#201000',
        grilleCoul: 'rgba(255,180,50,0.04)',
        lueurCoul: '#ffbb44',
        styleBloc: 'grain',
        ui: {
            bordureCanvas: '#ffbb44',
            couleurPrimaire: '#ffaa00',
            couleurScore: '#ffdd88',
            couleurAccent: '#dd8800',
            fondPanneau: 'rgba(255,180,50,0.05)',
            bordurePanneau: 'rgba(255,180,50,0.2)',
        },
        textes: {
            score: 'GRAINS',
            lignes: 'DUNES',
            niveau: 'STRATE',
            hold: 'OASIS',
            next: 'HORIZON',
            gameOver: 'ENSABLÉ',
            pause: 'MIRAGE',
            robo: 'SABLE',
            record: 'DUNE MAX',
        },
        musique: { tempo: 120, gamme: 'arabian', timbre: 'sawtooth', basse: true },
    },
    cyber: {
        id: 'cyber',
        nom: 'CYBER',
        icone: '⚡',
        niveauDeblocage: 18,
        couleursBlocs: [
            '#ff00ff',
            '#aa00ff',
            '#ff0099',
            '#cc00ee',
            '#8800cc',
            '#ff33cc',
            '#dd00ff',
        ],
        fondCiel: '#0a000f',
        fondSol: '#140020',
        grilleCoul: 'rgba(200,0,255,0.05)',
        lueurCoul: '#ff00ff',
        styleBloc: 'circuit',
        ui: {
            bordureCanvas: '#ff00ff',
            couleurPrimaire: '#aa00ff',
            couleurScore: '#ff33cc',
            couleurAccent: '#ff00ff',
            fondPanneau: 'rgba(200,0,255,0.06)',
            bordurePanneau: 'rgba(200,0,255,0.2)',
        },
        textes: {
            score: 'DONNÉES',
            lignes: 'PAQUETS',
            niveau: 'INSTANCE',
            hold: 'BUFFER',
            next: 'QUEUE',
            gameOver: 'CRASH',
            pause: 'STANDBY',
            robo: 'BOT-X',
            record: 'OVERCLOC MAX',
        },
        musique: { tempo: 160, gamme: 'chromatique', timbre: 'square', basse: true },
    },
    fuochi: {
        id: 'fuochi',
        nom: "FEUX D'ARTIFICE",
        icone: '🎆',
        niveauDeblocage: 21,
        couleursBlocs: [
            '#ff2244',
            '#ff8800',
            '#ffe600',
            '#00ff88',
            '#00aaff',
            '#aa00ff',
            '#ff00aa',
        ],
        fondCiel: '#02020a',
        fondSol: '#08081a',
        grilleCoul: 'rgba(255,255,100,0.04)',
        lueurCoul: '#ffe600',
        styleBloc: 'diamant',
        ui: {
            bordureCanvas: '#ffe600',
            couleurPrimaire: '#ff2244',
            couleurScore: '#00ff88',
            couleurAccent: '#00aaff',
            fondPanneau: 'rgba(255,200,0,0.05)',
            bordurePanneau: 'rgba(255,200,0,0.2)',
        },
        textes: {
            score: 'ÉCLATS',
            lignes: 'FUSÉES',
            niveau: 'INTENSITÉ',
            hold: 'CHARGEUR',
            next: 'MÈCHE',
            gameOver: 'ÉTEINT',
            pause: 'RETARD',
            robo: 'FLAMBEAU',
            record: "FEU D'ARTIFICE MAX",
        },
        musique: { tempo: 150, gamme: 'majeur', timbre: 'triangle', basse: true },
    },
    cosmos: {
        id: 'cosmos',
        nom: 'COSMOS',
        icone: '🌌',
        niveauDeblocage: 24,
        couleursBlocs: [
            '#7700ff',
            '#0055ff',
            '#00aaff',
            '#ff00aa',
            '#ff5500',
            '#ffcc00',
            '#00ffcc',
        ],
        fondCiel: '#000008',
        fondSol: '#000010',
        grilleCoul: 'rgba(100,50,255,0.04)',
        lueurCoul: '#7700ff',
        styleBloc: 'nebuleuse',
        ui: {
            bordureCanvas: '#7700ff',
            couleurPrimaire: '#0055ff',
            couleurScore: '#00ffcc',
            couleurAccent: '#7700ff',
            fondPanneau: 'rgba(100,0,255,0.06)',
            bordurePanneau: 'rgba(100,0,255,0.2)',
        },
        textes: {
            score: 'ÉNERGIE',
            lignes: 'ORBITES',
            niveau: 'DIMENSION',
            hold: 'STASE',
            next: 'NEXUS',
            gameOver: 'SINGULARITÉ',
            pause: 'DISTORSION',
            robo: 'COSMO',
            record: 'MAGNITUDE MAX',
        },
        musique: { tempo: 105, gamme: 'whole_tone', timbre: 'sine', basse: false },
    },
};

export const RELIQUES = {
    classique: {
        nom: 'OMEGA',
        icone: '⊗',
        description: 'Bloc 2×2 qui compte double pour chaque ligne',
        couleur: '#ffffff',
        forme: [
            [1, 1],
            [1, 1],
        ],
        effet: 'doublon',
    },
    lave: {
        nom: 'MAGMA',
        icone: '💥',
        description: "Détruit un rayon de 2 cases autour du point d'impact",
        couleur: '#ff4500',
        forme: [
            [0, 1, 0],
            [1, 1, 1],
            [0, 1, 0],
        ],
        effet: 'explosion',
    },
    ocean: {
        nom: 'BULLE',
        icone: '🫧',
        description: "Remonte de 2 rangées après s'être posée",
        couleur: '#00cfff',
        forme: [
            [0, 1, 0],
            [1, 1, 1],
        ],
        effet: 'flottaison',
    },
    foret: {
        nom: 'SPORE',
        icone: '🌱',
        description: 'Fait pousser 4 cellules dans les espaces vides adjacents',
        couleur: '#00cc44',
        forme: [
            [1, 0, 1],
            [0, 1, 0],
            [1, 0, 1],
        ],
        effet: 'croissance',
    },
    glace: {
        nom: 'BLIZZARD',
        icone: '❄️',
        description: 'Ajoute une ligne vide sous le tas (repousse tout vers le haut)',
        couleur: '#aaeeff',
        forme: [[1, 1, 1, 1]],
        effet: 'blizzard',
    },
    desert: {
        nom: 'SABLE',
        icone: '⌛',
        description: 'Remplit automatiquement les 3 trous les plus profonds du plateau',
        couleur: '#ffbb44',
        forme: [
            [1, 1, 0],
            [0, 1, 1],
            [0, 0, 1],
        ],
        effet: 'remplissage',
    },
    cyber: {
        nom: 'VIRUS',
        icone: '⚠',
        description: "Efface une demi-ligne aléatoire (libère de l'espace)",
        couleur: '#ff00ff',
        forme: [
            [1, 0, 1],
            [0, 1, 0],
            [1, 0, 1],
        ],
        effet: 'hack',
    },
    fuochi: {
        nom: 'FUSÉE',
        icone: '🚀',
        description: "Détruit entièrement la colonne d'atterrissage",
        couleur: '#ffe600',
        forme: [
            [0, 1, 0],
            [0, 1, 0],
            [1, 1, 1],
        ],
        effet: 'colonne',
    },
    cosmos: {
        nom: 'NEXUS',
        icone: '✦',
        description: "Compacte le plateau : toutes les cellules tombent d'un rang",
        couleur: '#7700ff',
        forme: [
            [0, 1, 0],
            [1, 1, 1],
            [0, 1, 0],
        ],
        effet: 'gravite',
    },
};

export const METEO_BIOMES = {
    classique: {
        nom: 'TURBO',
        icone: '⚡',
        alerte: 'ACCÉLÉRATION IMMINENTE',
        actif: 'TURBO ACTIVÉ',
        couleur: '#ffe600',
        duree: 12000,
        effet: 'acceleration',
    },
    lave: {
        nom: 'ÉRUPTION',
        icone: '🌋',
        alerte: 'ÉRUPTION IMMINENTE',
        actif: 'LAVE EN FUSION',
        couleur: '#ff4500',
        duree: 0,
        effet: 'eruption',
    },
    ocean: {
        nom: 'COURANT',
        icone: '🌊',
        alerte: 'COURANT SOUS-MARIN',
        actif: 'DÉRIVE EN COURS',
        couleur: '#00cfff',
        duree: 18000,
        effet: 'courant',
    },
    foret: {
        nom: 'GERMINATION',
        icone: '🌿',
        alerte: 'CROISSANCE SAUVAGE',
        actif: 'LA FORÊT ENVAHIT',
        couleur: '#00cc44',
        duree: 0,
        effet: 'germination',
    },
    glace: {
        nom: 'BLIZZARD',
        icone: '🌨',
        alerte: 'TEMPÊTE ARCTIQUE',
        actif: 'VISIBILITÉ RÉDUITE',
        couleur: '#aaeeff',
        duree: 14000,
        effet: 'blizzard',
    },
    desert: {
        nom: 'TEMPÊTE',
        icone: '🏜',
        alerte: 'TEMPÊTE DE SABLE',
        actif: 'VISIBILITÉ NULLE',
        couleur: '#ffbb44',
        duree: 10000,
        effet: 'tempete',
    },
    cyber: {
        nom: 'INVERSION',
        icone: '⚠',
        alerte: 'CORRUPTION DÉTECTÉE',
        actif: 'CONTRÔLES INVERSÉS',
        couleur: '#ff00ff',
        duree: 9000,
        effet: 'inversion',
    },
    fuochi: {
        nom: 'BARRAGE',
        icone: '🎆',
        alerte: 'BARRAGE DE FEU',
        actif: "FEU D'ARTIFICE",
        couleur: '#ffe600',
        duree: 0,
        effet: 'barrage',
    },
    cosmos: {
        nom: 'MICROGRAVITÉ',
        icone: '🌌',
        alerte: 'ANOMALIE GRAVITATIONNELLE',
        actif: 'MICROGRAVITÉ',
        couleur: '#7700ff',
        duree: 20000,
        effet: 'microgravite',
    },
};

export const ORDRE_BIOMES = [
    'classique',
    'lave',
    'ocean',
    'foret',
    'glace',
    'desert',
    'cyber',
    'fuochi',
    'cosmos',
];

export const LAYOUT = {
    panneauLargeur: 128,
    gap: 10,
    plateauLargeur: 320,
    plateauHauteur: 640,
    previewHauteur: 200,
    holdHauteur: 72,
    statsHauteur: 280,
    mascotteHauteur: 130,
    pauseHauteur: 40,
    paddingVertical: 16,
    margeScale: 20,
    hauteurControles: 132,
};

export const TABLE_KICK_STANDARD = [
    [
        [0, 0],
        [-1, 0],
        [-1, -1],
        [0, 2],
        [-1, 2],
    ],
    [
        [0, 0],
        [1, 0],
        [1, 1],
        [0, -2],
        [1, -2],
    ],
    [
        [0, 0],
        [1, 0],
        [1, -1],
        [0, 2],
        [1, 2],
    ],
    [
        [0, 0],
        [-1, 0],
        [-1, 1],
        [0, -2],
        [-1, -2],
    ],
];

export const TABLE_KICK_I = [
    [
        [0, 0],
        [-2, 0],
        [1, 0],
        [-2, -1],
        [1, 2],
    ],
    [
        [0, 0],
        [-1, 0],
        [2, 0],
        [-1, 2],
        [2, -1],
    ],
    [
        [0, 0],
        [2, 0],
        [-1, 0],
        [2, 1],
        [-1, -2],
    ],
    [
        [0, 0],
        [1, 0],
        [-2, 0],
        [1, -2],
        [-2, 1],
    ],
];

export const TETROMINOS = {
    I: {
        rotations: [
            [
                [0, 0, 0, 0],
                [1, 1, 1, 1],
                [0, 0, 0, 0],
                [0, 0, 0, 0],
            ],
            [
                [0, 0, 1, 0],
                [0, 0, 1, 0],
                [0, 0, 1, 0],
                [0, 0, 1, 0],
            ],
            [
                [0, 0, 0, 0],
                [0, 0, 0, 0],
                [1, 1, 1, 1],
                [0, 0, 0, 0],
            ],
            [
                [0, 1, 0, 0],
                [0, 1, 0, 0],
                [0, 1, 0, 0],
                [0, 1, 0, 0],
            ],
        ],
    },
    O: {
        rotations: [
            [
                [1, 1],
                [1, 1],
            ],
        ],
    },
    T: {
        rotations: [
            [
                [0, 1, 0],
                [1, 1, 1],
                [0, 0, 0],
            ],
            [
                [0, 1, 0],
                [0, 1, 1],
                [0, 1, 0],
            ],
            [
                [0, 0, 0],
                [1, 1, 1],
                [0, 1, 0],
            ],
            [
                [0, 1, 0],
                [1, 1, 0],
                [0, 1, 0],
            ],
        ],
    },
    S: {
        rotations: [
            [
                [0, 1, 1],
                [1, 1, 0],
                [0, 0, 0],
            ],
            [
                [0, 1, 0],
                [0, 1, 1],
                [0, 0, 1],
            ],
            [
                [0, 0, 0],
                [0, 1, 1],
                [1, 1, 0],
            ],
            [
                [1, 0, 0],
                [1, 1, 0],
                [0, 1, 0],
            ],
        ],
    },
    Z: {
        rotations: [
            [
                [1, 1, 0],
                [0, 1, 1],
                [0, 0, 0],
            ],
            [
                [0, 0, 1],
                [0, 1, 1],
                [0, 1, 0],
            ],
            [
                [0, 0, 0],
                [1, 1, 0],
                [0, 1, 1],
            ],
            [
                [0, 1, 0],
                [1, 1, 0],
                [1, 0, 0],
            ],
        ],
    },
    J: {
        rotations: [
            [
                [1, 0, 0],
                [1, 1, 1],
                [0, 0, 0],
            ],
            [
                [0, 1, 1],
                [0, 1, 0],
                [0, 1, 0],
            ],
            [
                [0, 0, 0],
                [1, 1, 1],
                [0, 0, 1],
            ],
            [
                [0, 1, 0],
                [0, 1, 0],
                [1, 1, 0],
            ],
        ],
    },
    L: {
        rotations: [
            [
                [0, 0, 1],
                [1, 1, 1],
                [0, 0, 0],
            ],
            [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 1],
            ],
            [
                [0, 0, 0],
                [1, 1, 1],
                [1, 0, 0],
            ],
            [
                [1, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
        ],
    },
};

export const TOUCHES_DEFAUT = {
    gauche: 'ArrowLeft',
    droite: 'ArrowRight',
    bas: 'ArrowDown',
    tournerH: 'ArrowUp',
    tournerAH: 'KeyX',
    chute: 'Space',
    hold: 'KeyC',
    pause: 'KeyP',
};
