// Données narratives du Mode Histoire — "La Fragmentation"

export const PERSONNAGES = {
    robo: {
        id: 'robo',
        nom: 'ROBO',
        description: 'Gardien de la Trame. Construit en urgence par VERA.',
    },
    vera: {
        id: 'vera',
        nom: 'VERA',
        titreLong: 'Vectorielle Experte en Réalité Architecturée',
        description: 'Créatrice de Robo. Piégée dans la Trame Primordiale.',
    },
    distorsion: {
        id: 'distorsion',
        nom: 'LA DISTORSION',
        description: "Née de l'accumulation de millions de lignes incomplètes.",
    },
};

export const CHAPITRES = [
    {
        id: 'prologue',
        numero: 0,
        titre: 'PROLOGUE',
        sousTitre: "L'Éveil de Robo",
        couleur: '#00f5ff',
        biomes: ['classique'],
        bossId: null,
        debloque: true,
        textesTransition: [
            'Un signal. Puis la conscience.',
            "Je suis Robo. Je viens d'être activé.",
            'VERA me parle. Sa voix est — connexion perdue.',
            'Il y a quelque chose à faire. Je dois trouver quoi.',
        ],
    },
    {
        id: 'chapitre_1',
        numero: 1,
        titre: 'CHAPITRE I',
        sousTitre: 'Le Feu des Origines',
        couleur: '#ff4500',
        biomes: ['lave', 'rouille'],
        bossId: 'brasier',
        conditionDeblocage: { chapitrePrec: 'prologue' },
        textesTransition: [
            "Le feu brûle plus fort qu'il ne devrait.",
            'La corruption a une odeur. Du métal surchauffé.',
            'VERA est passée ici. Elle a laissé quelque chose.',
        ],
    },
    {
        id: 'chapitre_2',
        numero: 2,
        titre: 'CHAPITRE II',
        sousTitre: 'Le Silence des Profondeurs',
        couleur: '#00cfff',
        biomes: ['ocean', 'foret', 'glace'],
        bossId: 'sentinelle',
        conditionDeblocage: { chapitrePrec: 'chapitre_1' },
        textesTransition: [
            'Sous la surface, tout est plus calme.',
            "Mais le calme n'est pas la paix.",
            'Il y a une voix dans les profondeurs. Elle essaie de me dire quelque chose.',
        ],
    },
    {
        id: 'chapitre_3',
        numero: 3,
        titre: 'CHAPITRE III',
        sousTitre: 'La Mémoire Perdue',
        couleur: '#ffbb44',
        biomes: ['desert', 'eclipse', 'cyber'],
        bossId: 'archiviste',
        conditionDeblocage: { chapitrePrec: 'chapitre_2' },
        textesTransition: [
            "Le désert garde tout. Le problème, c'est qu'on ne sait pas quoi chercher.",
            "Dans CYBER, j'ai trouvé son laboratoire.",
            "VERA n'est pas morte. Elle est piégée.",
        ],
    },
    {
        id: 'chapitre_4',
        numero: 4,
        titre: 'CHAPITRE IV',
        sousTitre: 'La Fracture de la Trame',
        couleur: '#b400ff',
        biomes: ['fuochi', 'cosmos', 'vide'],
        bossId: 'avantgarde',
        conditionDeblocage: { chapitrePrec: 'chapitre_3' },
        textesTransition: [
            "Les feux d'artifice célèbrent quelque chose. Je ne sais pas quoi.",
            "Au bord du cosmos, il n'y a plus rien à voir.",
            "Le Vide n'est pas vide. Il est rempli d'absence.",
        ],
    },
    {
        id: 'finale',
        numero: 5,
        titre: 'FINALE',
        sousTitre: 'La Résolution',
        couleur: '#ff006e',
        biomes: ['cosmos'],
        bossId: 'distorsion',
        conditionDeblocage: { chapitrePrec: 'chapitre_4' },
        textesTransition: [
            'Je comprends maintenant.',
            "La Distorsion n'est pas mon ennemie.",
            'Elle est ce que je deviendrais si personne ne me complétait.',
        ],
    },
];

export const BOSS = {
    brasier: {
        id: 'brasier',
        nom: 'LE BRASIER PERPÉTUEL',
        icone: '🔥',
        biomeId: 'lave',
        couleur: '#ff4500',
        pvMax: 14,
        attaqueIntervalleMs: 22000,
        attaqueType: 'rangee_braise',
        portrait: 'drawBossPortraitBrasier',
        texteApparition: 'Je suis tout ce que vous avez laissé brûler.',
        texteDefaite: 'Vous... complétez... tout.',
    },
    sentinelle: {
        id: 'sentinelle',
        nom: 'LA SENTINELLE DES GLACES',
        icone: '❄️',
        biomeId: 'glace',
        couleur: '#aaeeff',
        pvMax: 12,
        attaqueIntervalleMs: 19000,
        attaqueType: 'colonne_gelee',
        nbColonnesGelees: 2,
        dureeGelee: 8000,
        portrait: 'drawBossPortraitSentinelle',
        texteApparition: 'Arrêtez. Arrêtez tout. Le gel préserve.',
        texteDefaite: 'Le temps... ne peut pas... tout arrêter.',
    },
    archiviste: {
        id: 'archiviste',
        nom: "L'ARCHIVISTE CORROMPU",
        icone: '⚠',
        biomeId: 'cyber',
        couleur: '#ff00ff',
        pvMax: 14,
        attaqueIntervalleMs: 15000,
        attaqueType: 'multi_phase',
        phases: [
            { pvSeuil: 13, type: 'inverser_controles', dureeMs: 6000 },
            { pvSeuil: 7, type: 'faux_fantome', dureeMs: 8000 },
        ],
        portrait: 'drawBossPortraitArchiviste',
        texteApparition: 'Les archives ne mentent pas. Toi, si.',
        texteDefaite: 'Erreur_404: logique_introuvable.',
    },
    avantgarde: {
        id: 'avantgarde',
        nom: "L'AVANT-GARDE",
        icone: '🌀',
        biomeId: 'cosmos',
        couleur: '#7700ff',
        pvMax: 18,
        attaqueIntervalleMs: 12000,
        attaqueType: 'combinaison',
        attaquesDisponibles: ['rangee_braise', 'colonne_gelee', 'inverser_controles'],
        portrait: 'drawBossPortraitAvantgarde',
        texteApparition: 'La Distorsion vous attend. Je vous prépare.',
        texteDefaite: 'Vous... êtes prêt. Elle... aussi.',
    },
    distorsion: {
        id: 'distorsion',
        nom: 'LA DISTORSION',
        icone: '∞',
        biomeId: 'cosmos',
        couleur: '#ff006e',
        pvMax: 32,
        attaqueIntervalleMs: 13000,
        attaqueType: 'rangee_braise',
        phases: [
            { pvSeuil: 32, attaqueType: 'rangee_braise' },
            { pvSeuil: 24, attaqueType: 'combinaison_glace_glitch' },
            { pvSeuil: 12, attaqueType: 'distorsion_plateau' },
        ],
        portrait: 'drawBossPortraitDistorsion',
        texteApparition: "Enfin. Tu comprends, n'est-ce pas ? Tout cela est inutile.",
        texteDefaite: "J'ai... perdu... cette fois.",
        texteDefaite_normal: "J'ai... perdu... cette fois.",
        texteDefaite_vrai: "Tu m'as... complétée.",
        texteDefaite_secret: 'VERA... dit bonjour.',
        conditionFinSecrete: {
            laisserRemplirA50SansClearer: true,
            dureeAttente: 30000,
        },
    },
};

export const JOURNAUX_VERA = [
    {
        id: 'journal_1',
        numero: 1,
        titre: 'TRANSMISSION 01',
        sousTitre: 'Inferno — Jour inconnu',
        biomeId: 'lave',
        condition: 'effacer_10_lignes_biome',
        texte: [
            "Je l'ai trouvé. La source.",
            "Elle n'est pas où je croyais.",
            "Ce n'est pas une anomalie technique.",
            "C'est quelque chose qui souffre.",
        ],
        illustration: 'dessinerJournalVera1',
    },
    {
        id: 'journal_2',
        numero: 2,
        titre: 'TRANSMISSION 02',
        sousTitre: 'La Rouille — Atelier abandonné',
        biomeId: 'rouille',
        condition: 'effacer_8_lignes_biome',
        texte: [
            "Ces machines n'auraient pas dû continuer de fonctionner.",
            'Et pourtant. Elles produisent des pièces.',
            'Des pièces que personne ne commande.',
            "Comme si elles attendaient quelqu'un.",
        ],
        illustration: 'dessinerJournalVera2',
    },
    {
        id: 'journal_3',
        numero: 3,
        titre: 'TRANSMISSION 03',
        sousTitre: 'Abysses — Profondeur 400m',
        biomeId: 'ocean',
        condition: 'effacer_10_lignes_biome',
        texte: [
            "Elle m'a répondu.",
            "Je n'ai pas compris sa langue.",
            "Mais j'ai compris sa douleur.",
            "Elle n'attaque pas. Elle se défend.",
        ],
        illustration: 'dessinerJournalVera3',
    },
    {
        id: 'journal_4',
        numero: 4,
        titre: 'TRANSMISSION 04',
        sousTitre: 'La Canopée — Quelque part en hauteur',
        biomeId: 'foret',
        condition: 'effacer_10_lignes_biome',
        texte: [
            "Elle m'a montré sa forme réelle.",
            'Pas un monstre. Une accumulation.',
            'Des millions de frustrations, cristallisées.',
            "Qui d'entre nous aurait résisté ?",
        ],
        illustration: 'dessinerJournalVera4',
    },
    {
        id: 'journal_5',
        numero: 5,
        titre: 'TRANSMISSION 05',
        sousTitre: 'Arctique — Après la Sentinelle',
        biomeId: 'glace',
        condition: 'debloquer_apres_boss_sentinelle',
        texte: [
            "J'ai une théorie.",
            'Si compléter des lignes renforce la Trame,',
            "alors laisser une ligne incomplète l'affaiblit.",
            "La Distorsion n'est pas née d'une erreur. Elle est née d'un choix.",
        ],
        illustration: 'dessinerJournalVera5',
    },
    {
        id: 'journal_6',
        numero: 6,
        titre: 'TRANSMISSION 06',
        sousTitre: 'Le Désert — Incomplet',
        biomeId: 'desert',
        condition: 'effacer_10_lignes_biome',
        texte: [
            'Ce fragment est endommagé.',
            "Je peux lire : '...pas la détruire... com—'",
            "'—prendre ce qu'elle res—'",
            'Le reste est du sable.',
        ],
        illustration: 'dessinerJournalVera6',
        estEndommage: true,
    },
    {
        id: 'journal_7',
        numero: 7,
        titre: 'TRANSMISSION 07',
        sousTitre: 'CYBER — Laboratoire de VERA',
        biomeId: 'cyber',
        condition: 'trouver_laboratoire_vera',
        texte: [
            'Robo.',
            "Si tu lis ceci, c'est que tu es arrivé jusqu'ici.",
            'Je suis fière de toi. Je ne pensais pas que tu en serais capable.',
            "Maintenant : je vais entrer dans la Trame. Ne m'attends pas.",
        ],
        illustration: 'dessinerJournalVera7',
        estMessageDirect: true,
    },
    {
        id: 'journal_8',
        numero: 8,
        titre: 'TRANSMISSION 08',
        sousTitre: 'Cosmos — Bord de la Trame',
        biomeId: 'cosmos',
        condition: 'effacer_12_lignes_biome',
        texte: [
            'Robo. Si tu trouves ceci,',
            "c'est que je n'ai pas réussi à revenir.",
            "Mais j'ai laissé quelque chose dans la Trame.",
            'Une ligne. Incomplète. Exprès.',
        ],
        illustration: 'dessinerJournalVera8',
    },
    {
        id: 'journal_9',
        numero: 9,
        titre: 'TRANSMISSION 09',
        sousTitre: 'Le Vide — Dernier signal',
        biomeId: 'vide',
        condition: 'effacer_8_lignes_biome',
        texte: [
            "La ligne incomplète que j'ai laissée —",
            "c'est une porte.",
            'Pour y entrer, tu dois faire ce qui te coûte le plus :',
            'laisser quelque chose inachevé.',
        ],
        illustration: 'dessinerJournalVera9',
    },
];

export const MONDES_CACHES = {
    miroir: {
        id: 'miroir',
        nom: 'LE MIROIR',
        conditions: [
            { type: 'boss_vaincu', bossId: 'archiviste' },
            { type: 'pattern_biome', biomeId: 'cyber', pattern: 'tetris_triple' },
        ],
        conditionsTexte: [
            "Vaincre l'Archiviste Corrompu",
            'Dans CYBER : réaliser 3 Tetris consécutifs',
        ],
    },
    trame: {
        id: 'trame',
        nom: 'LA TRAME PRIMORDIALE',
        conditions: [
            { type: 'monde_cache_complete', mondeId: 'miroir' },
            { type: 'tous_journaux_trouves' },
            { type: 'tous_boss_sans_continue' },
            { type: 'action_speciale_boss', bossId: 'distorsion', action: 'attendre_incomplet' },
        ],
        conditionsTexte: [
            'Compléter LE MIROIR',
            'Trouver tous les journaux de VERA',
            'Vaincre tous les boss sans Continue',
            'Dans la Finale : ne pas effacer pendant 30 secondes',
        ],
    },
    paradoxe: {
        id: 'paradoxe',
        nom: 'LE PARADOXE',
        ultraSecret: true,
        conditions: [
            { type: 'fin_obtenue', finId: 'fin_secrete' },
            {
                type: 'action_speciale_biome',
                biomeId: 'classique',
                action: 'trois_tops_volontaires_sans_ligne',
            },
        ],
        conditionsTexte: ['Obtenir la Fin Secrète', 'Dans le Prologue : mystère'],
    },
};

export const FINS = {
    fin_normale: {
        id: 'fin_normale',
        titre: 'FIN : LE CYCLE',
        texte: [
            'La Distorsion est vaisseau.',
            'La Trame tient. VERA est libre.',
            "Dans mille ans, peut-être, quelqu'un d'autre devra refaire le chemin.",
            'Robo pose la dernière pièce. Le plateau est vide.',
            "Pour la première fois, il comprend que c'était ça, le but.",
        ],
    },
    fin_vraie: {
        id: 'fin_vraie',
        titre: "FIN : L'HARMONIE",
        condition: { mondeCache: 'miroir' },
        texte: [
            "Robo n'a pas détruit La Distorsion.",
            'Il lui a tendu la main.',
            "La complétion et l'incomplétude forment un nouveau type de Trame.",
            'Plus fragile. Plus honnête.',
            'VERA sourit pour la première fois depuis longtemps.',
        ],
    },
    fin_secrete: {
        id: 'fin_secrete',
        titre: 'FIN : LA LIGNE PARFAITE',
        condition: { mondeCache: 'trame' },
        texte: [
            'La ligne incomplète de VERA.',
            'Robo la complète. Doucement. Sans hâte.',
            "La Distorsion ressent quelque chose qu'elle n'a jamais ressenti :",
            "la satisfaction d'une ligne effacée.",
            'Elle pleure. En binaire. 0 et 1.',
        ],
    },
};

export const ETAT_HISTOIRE_VIDE = {
    chapitreActuel: 'prologue',
    mondesCompletes: [],
    bossVaincus: [],
    journauxTrouves: [],
    mondesCachesDebloques: [],
    conditionsMiroir: {
        bossArchivisteVaincu: false,
        tetrisTriplesCyber: 0,
    },
    conditionsTrame: {
        miroirComplete: false,
        tousJournauxTrouves: false,
        tousBossSansContinue: true,
        actionDistorsionFaite: false,
    },
    conditionsParadoxe: {
        finSecreteObtenue: false,
        topsVolontairesPrologue: 0,
    },
    finObtenue: null,
    toutesFinObtenues: [],
    nbContinuesUtilises: 0,
    enModeHistoire: false,
    mondesDejaMontres: [],
    laboDecouvert: false,
    fragmentsVusIds: [],
    prouessesHistoire: {
        blocksRouillesMax: 0,
        lignesEclipseBasseMax: 0,
        lignesVideMax: 0,
        precisionMiroirMax: 0,
        meilleurTimerBossMs: Infinity,
    },
};

// ============================================================
// SÉQUENCE NARRATIVE COMPLÈTE
// ============================================================
export const SEQUENCE_HISTOIRE = [
    {
        id: 'monde_prologue',
        biomeId: 'classique',
        chapitreId: 'prologue',
        ordreGlobal: 1,
        nomAffiche: "L'ÉVEIL",
        estBoss: false,
        textesEntree: [
            'Un signal. Puis la conscience.',
            "Je suis Robo. Je viens d'être activé.",
            'VERA me parle. Sa voix est — connexion perdue.',
            'Il y a quelque chose à faire.',
        ],
    },
    {
        id: 'monde_lave',
        biomeId: 'lave',
        chapitreId: 'chapitre_1',
        ordreGlobal: 2,
        nomAffiche: 'INFERNO',
        estBoss: false,
        textesEntree: ["Le feu brûle plus fort qu'il ne devrait."],
    },
    {
        id: 'monde_rouille',
        biomeId: 'rouille',
        chapitreId: 'chapitre_1',
        ordreGlobal: 3,
        nomAffiche: 'LA ROUILLE',
        estBoss: false,
        textesEntree: ["Ces machines n'auraient pas dû continuer de fonctionner."],
    },
    {
        id: 'monde_boss_1',
        biomeId: 'lave',
        chapitreId: 'chapitre_1',
        ordreGlobal: 4,
        nomAffiche: 'LE BRASIER',
        estBoss: true,
        bossId: 'brasier',
        textesEntree: [
            'Je sens sa chaleur avant de le voir.',
            'Le Brasier Perpétuel. Il brûle depuis plus longtemps que les mondes.',
        ],
    },
    {
        id: 'monde_ocean',
        biomeId: 'ocean',
        chapitreId: 'chapitre_2',
        ordreGlobal: 5,
        nomAffiche: 'ABYSSES',
        estBoss: false,
        textesEntree: ['Sous la surface, tout est plus calme.'],
    },
    {
        id: 'monde_foret',
        biomeId: 'foret',
        chapitreId: 'chapitre_2',
        ordreGlobal: 6,
        nomAffiche: 'LA CANOPÉE',
        estBoss: false,
        textesEntree: ['La forêt me regarde. Je ne suis pas sûr de ce que ça signifie.'],
    },
    {
        id: 'monde_glace',
        biomeId: 'glace',
        chapitreId: 'chapitre_2',
        ordreGlobal: 7,
        nomAffiche: 'ARCTIQUE',
        estBoss: false,
        textesEntree: ["Le froid ne me dérange pas. L'immobilité, si."],
    },
    {
        id: 'monde_boss_2',
        biomeId: 'glace',
        chapitreId: 'chapitre_2',
        ordreGlobal: 8,
        nomAffiche: 'LA SENTINELLE',
        estBoss: true,
        bossId: 'sentinelle',
        textesEntree: [
            'Elle ne bougera pas.',
            "Elle pense que l'immobilité est la sécurité.",
            'Elle a tort.',
        ],
    },
    {
        id: 'monde_desert',
        biomeId: 'desert',
        chapitreId: 'chapitre_3',
        ordreGlobal: 9,
        nomAffiche: 'LE DÉSERT',
        estBoss: false,
        textesEntree: ["Le désert garde tout. Même ce qu'on voudrait oublier."],
    },
    {
        id: 'monde_eclipse',
        biomeId: 'eclipse',
        chapitreId: 'chapitre_3',
        ordreGlobal: 10,
        nomAffiche: "L'ÉCLIPSE",
        estBoss: false,
        textesEntree: ["Ce monde ne sait pas s'il fait nuit ou jour.", 'Je comprends.'],
    },
    {
        id: 'monde_cyber',
        biomeId: 'cyber',
        chapitreId: 'chapitre_3',
        ordreGlobal: 11,
        nomAffiche: 'CYBER',
        estBoss: false,
        textesEntree: ['Son laboratoire est ici.', 'Elle a laissé quelque chose pour moi.'],
    },
    {
        id: 'monde_boss_3',
        biomeId: 'cyber',
        chapitreId: 'chapitre_3',
        ordreGlobal: 12,
        nomAffiche: "L'ARCHIVISTE",
        estBoss: true,
        bossId: 'archiviste',
        textesEntree: [
            'Il garde les archives.',
            "Il ne veut pas que je lise ce qu'elles contiennent.",
        ],
    },
    {
        id: 'monde_fuochi',
        biomeId: 'fuochi',
        chapitreId: 'chapitre_4',
        ordreGlobal: 13,
        nomAffiche: "FEUX D'ARTIFICE",
        estBoss: false,
        textesEntree: ["Quelqu'un célèbre quelque chose.", 'Je ne sais pas quoi.'],
    },
    {
        id: 'monde_cosmos',
        biomeId: 'cosmos',
        chapitreId: 'chapitre_4',
        ordreGlobal: 14,
        nomAffiche: 'COSMOS',
        estBoss: false,
        textesEntree: ["Au bord du cosmos, il n'y a plus rien à voir.", 'Sauf elle.'],
    },
    {
        id: 'monde_vide',
        biomeId: 'vide',
        chapitreId: 'chapitre_4',
        ordreGlobal: 15,
        nomAffiche: 'LE VIDE',
        estBoss: false,
        textesEntree: [
            "Le Vide n'est pas vide.",
            "Il est rempli de ce que VERA m'a laissé.",
            'Une ligne. Incomplète. Exprès.',
        ],
    },
    {
        id: 'monde_boss_4',
        biomeId: 'cosmos',
        chapitreId: 'chapitre_4',
        ordreGlobal: 16,
        nomAffiche: "L'AVANT-GARDE",
        estBoss: true,
        bossId: 'avantgarde',
        textesEntree: [
            "Elle m'attend derrière.",
            'Celui-ci est son avant-poste.',
            'Je dois passer.',
        ],
    },
    {
        id: 'monde_finale',
        biomeId: 'cosmos',
        chapitreId: 'finale',
        ordreGlobal: 17,
        nomAffiche: 'LA DISTORSION',
        estBoss: true,
        bossId: 'distorsion',
        estFinale: true,
        textesEntree: [
            'Je comprends maintenant.',
            "La Distorsion n'est pas mon ennemie.",
            'Elle est ce que je deviendrais si personne ne me complétait.',
        ],
    },
    {
        id: 'monde_miroir',
        biomeId: 'miroir',
        chapitreId: null,
        ordreGlobal: 18,
        nomAffiche: 'LE MIROIR',
        estBoss: false,
        estCache: true,
        textesEntree: ["Ceci n'aurait pas dû exister.", 'Et pourtant.'],
    },
    {
        id: 'monde_trame',
        biomeId: 'trame',
        chapitreId: null,
        ordreGlobal: 19,
        nomAffiche: 'LA TRAME PRIMORDIALE',
        estBoss: false,
        estCache: true,
        estUltraSecret: true,
        textesEntree: ['VERA.', "Je t'ai trouvée."],
    },
    {
        id: 'monde_paradoxe',
        biomeId: 'classique',
        chapitreId: null,
        ordreGlobal: 20,
        nomAffiche: 'LE PARADOXE',
        estBoss: false,
        estCache: true,
        estUltraSecret: true,
        textesEntree: ['...'],
    },
];
