/**
 * Barrel public de l'état de jeu — réexporte store-core, store-etat-partie,
 * store-refs-canvas et helpers accessibilité. Point d'entrée unique pour la
 * logique solo/coop qui lit ou modifie l'état runtime.
 */
export {
    ECRANS,
    MAX_PARTICULES,
    DUREE_TRANSITION,
    NB_PARTICULES_AMBIANCE,
    CARACTERES_HEX,
    VERTS_FORET,
    etat,
    particules,
    particulesAmbiance,
    textesFlottants,
    secousse,
    flashVerrou,
    flashLignes,
    touchesActives,
    couleurAmbRgb,
    dasEtat,
} from './store-core.js';

export {
    obtenirBiomeActif,
    obtenirNiveauGlobal,
    obtenirCompteurPieces,
    obtenirSeuilProchRelique,
    obtenirReliqueEnAttente,
    obtenirReliqueActive,
    obtenirEcranActuel,
    obtenirTransitionAlpha,
    obtenirTransitionDebut,
    obtenirTempsAmbianceDecor,
    obtenirTouchDepart,
    obtenirLockDelayRestant,
    obtenirNbLockResets,
    obtenirPieceAuSol,
    obtenirSacPieces,
    obtenirEffetsReduits,
    obtenirFpsMoyen,
    obtenirIdFrame,
    obtenirBoucleActive,
    obtenirDernierTimestamp,
    obtenirAccumulateur,
    obtenirDerniereSecondeTemps,
    obtenirPrefererMoinsAnimations,
    definirBiomeActif,
    definirNiveauGlobal,
    ajouterNiveauGlobal,
    definirReliqueActive,
    definirReliqueEnAttente,
    definirCompteurPieces,
    incrementerCompteurPieces,
    definirSeuilProchRelique,
    definirEcranActuel,
    definirTransitionAlpha,
    definirTransitionDebut,
    definirCouleurAmbRgb,
    definirDerniereSecondeTemps,
    definirLockDelayRestant,
    definirNbLockResets,
    definirPieceAuSol,
    definirFpsMoyen,
    definirEffetsReduits,
    definirIdFrame,
    definirBoucleActive,
    definirDernierTimestamp,
    definirAccumulateur,
    definirTouchDepart,
    reinitialiserTempsAmbianceDecor,
    ajouterTempsAmbianceDecor,
} from './store-etat-partie.js';

export {
    obtenirCanvasPlateau,
    obtenirCtx,
    obtenirCanvasPreview,
    obtenirCtxPreview,
    obtenirCanvasReserve,
    obtenirCtxReserve,
    definirRefsCanvas,
} from './store-refs-canvas.js';

export {
    obtenirDaltonien,
    obtenirReduireEffetsAccessibilite,
    obtenirEffetsAccessibiliteReduits,
} from './accessibilite.js';
