/** Niveaux Architecte (nature) — export JSON via scripts/exporter-codex-archi.mjs. */
/** @typedef {import('../archi-donnees.js').NiveauArchi} NiveauArchi */

/** @type {NiveauArchi[]} */
export const NIVEAUX_ARCHI_NATURE = [
    {
        id: 'carre_classique',
        nom: 'LE CARRÉ',
        biome: 'classique',
        difficulte: 1,
        parPieces: 4,
        deblocage: 0,
        silhouette: ['....####..', '....####..', '....####..', '....####..'],
        pieces: [{ type: 'O', qte: 4 }],
    },
    {
        id: 'croix_classique',
        nom: 'LA CROIX',
        biome: 'classique',
        difficulte: 1,
        parPieces: 3,
        deblocage: 0,
        silhouette: ['....##....', '....##....', '..######..', '....##....', '....##....'],
        pieces: [
            { type: 'I', qte: 2 },
            { type: 'T', qte: 2 },
        ],
    },
    {
        id: 'coeur_classique',
        nom: 'LE CŒUR',
        biome: 'classique',
        difficulte: 2,
        parPieces: 5,
        deblocage: 400,
        silhouette: [
            '.###.###..',
            '.########.',
            '.########.',
            '..######..',
            '...####...',
            '....##....',
        ],
        pieces: [
            { type: 'O', qte: 2 },
            { type: 'S', qte: 2 },
            { type: 'Z', qte: 2 },
            { type: 'T', qte: 2 },
        ],
    },
    {
        id: 'flamme_lave',
        nom: 'LA FLAMME',
        biome: 'lave',
        difficulte: 2,
        parPieces: 4,
        deblocage: 500,
        silhouette: [
            '....##....',
            '...####...',
            '..######..',
            '..######..',
            '...####...',
            '....##....',
            '....##....',
        ],
        pieces: [
            { type: 'I', qte: 2 },
            { type: 'T', qte: 3 },
            { type: 'S', qte: 1 },
            { type: 'Z', qte: 1 },
        ],
    },
    {
        id: 'volcan_lave',
        nom: 'LE VOLCAN',
        biome: 'lave',
        difficulte: 3,
        parPieces: 6,
        deblocage: 700,
        silhouette: [
            '....##....',
            '...####...',
            '..######..',
            '.########.',
            '####..####',
            '##......##',
        ],
        pieces: [
            { type: 'I', qte: 2 },
            { type: 'L', qte: 2 },
            { type: 'J', qte: 2 },
            { type: 'T', qte: 2 },
            { type: 'O', qte: 1 },
        ],
    },
    {
        id: 'vague_ocean',
        nom: 'LA VAGUE',
        biome: 'ocean',
        difficulte: 2,
        parPieces: 5,
        deblocage: 600,
        silhouette: ['##......##', '###....###', '.###..###.', '..######..', '...####...'],
        pieces: [
            { type: 'S', qte: 2 },
            { type: 'Z', qte: 2 },
            { type: 'J', qte: 2 },
            { type: 'L', qte: 2 },
        ],
    },
    {
        id: 'poisson_ocean',
        nom: 'LE POISSON',
        biome: 'ocean',
        difficulte: 3,
        parPieces: 7,
        deblocage: 800,
        silhouette: ['##..###...', '##.#####..', '##.######.', '##.#####..', '##..###...'],
        pieces: [
            { type: 'O', qte: 3 },
            { type: 'L', qte: 2 },
            { type: 'J', qte: 2 },
            { type: 'I', qte: 1 },
        ],
    },
    {
        id: 'arbre_foret',
        nom: "L'ARBRE",
        biome: 'foret',
        difficulte: 2,
        parPieces: 5,
        deblocage: 700,
        silhouette: [
            '....##....',
            '...####...',
            '..######..',
            '.########.',
            '....##....',
            '....##....',
        ],
        pieces: [
            { type: 'T', qte: 3 },
            { type: 'I', qte: 1 },
            { type: 'L', qte: 2 },
            { type: 'J', qte: 2 },
        ],
    },
    {
        id: 'feuille_foret',
        nom: 'LA FEUILLE',
        biome: 'foret',
        difficulte: 3,
        parPieces: 6,
        deblocage: 900,
        silhouette: [
            '.....#....',
            '....###...',
            '...#####..',
            '..#######.',
            '...#####..',
            '....###...',
            '....##....',
        ],
        pieces: [
            { type: 'S', qte: 2 },
            { type: 'Z', qte: 2 },
            { type: 'T', qte: 3 },
            { type: 'I', qte: 2 },
        ],
    },
];
