export const PORTRAITS = {
    robo: {
        emoji: '🤖',
        couleur: '#00f5ff',
        nom: 'ROBO',
        fondId: 'robo',
        police: 'pixel',
        vitesseMs: 38,
        nomStyle: 'normal',
    },
    vera: {
        emoji: '👩‍🔬',
        couleur: '#ff006e',
        nom: 'VERA',
        fondId: 'vera',
        police: 'narratif',
        vitesseMs: 28,
        nomStyle: 'italic',
    },
    distorsion: {
        emoji: '∞',
        couleur: '#b400ff',
        nom: 'LA DISTORSION',
        fondId: 'distorsion',
        police: 'stats',
        vitesseMs: 18,
        nomStyle: 'glitch',
    },
    systeme: {
        emoji: '⚙',
        couleur: '#ffe600',
        nom: 'SYSTÈME',
        fondId: 'systeme',
        police: 'terminal',
        vitesseMs: 16,
        nomStyle: 'normal',
    },
    narrateur: {
        emoji: '✦',
        couleur: 'rgba(255,255,255,0.6)',
        nom: '',
        fondId: 'narrateur',
        police: 'ui',
        vitesseMs: 32,
        nomStyle: 'italic',
    },
    sentinelle: {
        emoji: '🧊',
        couleur: '#aaeeff',
        nom: 'SENTINELLE',
        fondId: 'sentinelle',
        police: 'stats',
        vitesseMs: 42,
        nomStyle: 'normal',
    },
    archiviste: {
        emoji: '📚',
        couleur: '#ff00ff',
        nom: 'ARCHIVISTE',
        fondId: 'archiviste',
        police: 'terminal',
        vitesseMs: 22,
        nomStyle: 'normal',
    },
    avantgarde: {
        emoji: '⚡',
        couleur: '#7700ff',
        nom: 'AVANT-GARDE',
        fondId: 'avantgarde',
        police: 'stats',
        vitesseMs: 30,
        nomStyle: 'normal',
    },
    brasier: {
        emoji: '🔥',
        couleur: '#ff4500',
        nom: 'LE BRASIER',
        fondId: 'brasier',
        police: 'stats',
        vitesseMs: 60,
        nomStyle: 'normal',
    },
    brasier_voix: {
        emoji: '🔥',
        couleur: '#ff4500',
        nom: 'LE BRASIER',
        fondId: 'brasier',
        police: 'stats',
        vitesseMs: 60,
        nomStyle: 'normal',
    },
    sentinelle_voix: {
        emoji: '❄️',
        couleur: '#aaeeff',
        nom: 'SENTINELLE',
        fondId: 'sentinelle',
        police: 'stats',
        vitesseMs: 70,
        nomStyle: 'normal',
    },
    archiviste_voix: {
        emoji: '📚',
        couleur: '#ff00ff',
        nom: 'ARCHIVISTE',
        fondId: 'archiviste',
        police: 'terminal',
        vitesseMs: 22,
        nomStyle: 'normal',
    },
};
