export const PREFIXE_STOCKAGE = 'derniereLigne_';
export const PREFIXE_LEGACY = 'tetrisNeo_';

export const CLES_STOCKAGE = new Set([
    'derniereLigne_volume',
    'derniereLigne_volumeMusique',
    'derniereLigne_muet',
    'derniereLigne_contraste',
    'derniereLigne_daltonien',
    'derniereLigne_reduireEffets',
    'derniereLigne_constellationClicSeul',
    'derniereLigne_mixBiomes',
    'derniereLigne_niveauGlobal',
    'derniereLigne_biomeActif',
    'derniereLigne_codex',
    'derniereLigne_codexVus',
    'derniereLigne_statsGlobales',
    'derniereLigne_profilDernier',
    'derniereLigne_histoire',
    'derniereLigne_histoireJournaux',
    'derniereLigne_histoireBoss',
    'derniereLigne_histoireFin',
    'derniereLigne_journalErreurs',
    'derniereLigne_introHistoireVue',
    'derniereLigne_tutorielVu',
    'derniereLigne_tutorielHistoireVu',
    'derniereLigne_tutorielLibreVu',
    'derniereLigne_tutorielCoopVu',
    'derniereLigne_tutorielArchitecteVu',
    'derniereLigne_tutorielOracleVu',
    'derniereLigne_tutorielDistorsionVu',
    'derniereLigne_touches',
    'derniereLigne_infobullesBiome',
    'derniereLigne_infobullesModesJeu',
    'derniereLigne_infobullesBoss',
    'derniereLigne_infobulleOracleCoop',
    'derniereLigne_infobulleGraceSpawn',
    'derniereLigne_defiJour',
    'derniereLigne_devActif',
    'derniereLigne_haptique',
    'derniereLigne_controlesTactiles',
    'derniereLigne_enchainementCampagne',
    'derniereLigne_syncCloudActif',
    'derniereLigne_syncCloudId',
    'derniereLigne_supabaseUrl',
    'derniereLigne_supabaseAnonKey',
]);

/** Préférences conservées lors d'une nouvelle partie. */
export const CLES_PREFERENCES = new Set([
    'derniereLigne_volume',
    'derniereLigne_volumeMusique',
    'derniereLigne_muet',
    'derniereLigne_contraste',
    'derniereLigne_daltonien',
    'derniereLigne_reduireEffets',
    'derniereLigne_constellationClicSeul',
    'derniereLigne_controlesTactiles',
    'derniereLigne_haptique',
    'derniereLigne_enchainementCampagne',
    'derniereLigne_mixBiomes',
    'derniereLigne_touches',
    'dl_migration_v1',
]);

export const MOTIFS_CLES_PROGRESSION = [
    /^derniereLigne_record_[a-z]+$/,
    /^derniereLigne_recniv_[a-z]+$/,
    /^derniereLigne_recordcoop_[a-z]+$/,
    /^derniereLigne_sprint_[a-z]+$/,
    /^derniereLigne_archi_[a-z_]+$/,
    /^derniereLigne_monde_histoire_[a-z_]+$/,
    /^tetrisNeo_record_[a-z]+$/,
    /^tetrisNeo_recniv_[a-z]+$/,
    /^tetrisNeo_recordcoop_[a-z]+$/,
    /^tetrisNeo_sprint_[a-z]+$/,
    /^tetrisNeo_archi_[a-z_]+$/,
    /^tetrisNeo_monde_histoire_[a-z_]+$/,
];

export const CLES_LEGACY = new Set([
    'tetrisNeo_volume',
    'tetrisNeo_volumeMusique',
    'tetrisNeo_muet',
    'tetrisNeo_contraste',
    'tetrisNeo_niveauGlobal',
    'tetrisNeo_biomeActif',
    'tetrisNeo_codex',
    'tetrisNeo_codexVus',
    'tetrisNeo_statsGlobales',
    'tetrisNeo_profilDernier',
    'tetrisNeo_histoire',
    'tetrisNeo_histoireJournaux',
    'tetrisNeo_histoireBoss',
    'tetrisNeo_histoireFin',
    'tetrisNeo_journalErreurs',
]);
