import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        include: ['tests/**/*.test.mjs'],
        setupFiles: ['tests/setup.mjs'],
        coverage: {
            provider: 'v8',
            include: [
                'js/logique-pure.js',
                'js/progression.js',
                'js/progression-stockage.js',
                'js/progression-records.js',
                'js/progression-histoire.js',
                'js/boss-attaques.js',
                'js/registre-modes.js',
                'js/piece-jeu.js',
                'js/moteur-piece.js',
                'js/achievements.js',
                'js/logique-partie.js',
                'js/logique-partie-verrouillage.js',
                'js/logique-partie-mouvement.js',
                'js/logique-partie-score.js',
                'js/logique-partie-hold.js',
                'js/planificateur-raf.js',
                'js/oracle-jeu.js',
                'js/coop-logique.js',
                'js/archi-logique.js',
                'js/vivant.js',
                'js/vivant-strategies.js',
                'js/actions-piece-communes.js',
                'js/mecaniques-histoire.js',
                'js/mecaniques-histoire-queries.js',
                'js/mecaniques-histoire-rouille.js',
                'js/mecaniques-histoire-eclipse.js',
                'js/mecaniques-histoire-vide.js',
                'js/mecaniques-histoire-trame.js',
                'js/mecaniques-histoire-miroir.js',
                'js/rendu-fond-biome-donnees.js',
                'js/rendu-fond-biome-particules.js',
                'js/histoire-map-panneau-details.js',
                'js/histoire-map-interactions.js',
                'js/conditions-secrets.js',
                'js/histoire-etat.js',
                'js/histoire-manager.js',
                'js/histoire-manager-completion.js',
                'js/boss-jeu.js',
                'js/rendu-robo.js',
                'js/mascotte-robo.js',
                'js/portraits-cutscene.js',
                'js/partie-fin.js',
                'js/histoire-intro.js',
                'js/charger-histoire-textes.js',
                'js/layout-jeu.js',
                'js/game-feel-jeu.js',
                'js/coop-game-feel.js',
                'js/gestionnaire-difficulte.js',
                'js/prechargement-medias.js',
                'js/moteur-config-actions.js',
            ],
            thresholds: {
                lines: 54,
                functions: 56,
                statements: 52,
                branches: 46,
            },
        },
    },
});
