import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        include: ['tests/**/*.test.mjs'],
        setupFiles: ['tests/setup.mjs'],
        coverage: {
            provider: 'v8',
            include: [
                'js/logique-pure.js',
                'js/progression.js',
                'js/progression-stockage.js',
                'js/progression-records.js',
                'js/progression-histoire.js',
                'js/boss-attaques.js',
                'js/registre-modes.js',
                'js/piece-jeu.js',
                'js/moteur-piece.js',
                'js/achievements.js',
                'js/logique-partie.js',
                'js/oracle-jeu.js',
                'js/coop-logique.js',
                'js/archi-logique.js',
                'js/vivant.js',
                'js/vivant-strategies.js',
                'js/actions-piece-communes.js',
                'js/mecaniques-histoire.js',
                'js/conditions-secrets.js',
                'js/histoire-etat.js',
                'js/histoire-manager.js',
                'js/histoire-manager-completion.js',
                'js/boss-jeu.js',
                'js/rendu-robo.js',
                'js/mascotte-robo.js',
                'js/portraits-cutscene.js',
                'js/partie-fin.js',
                'js/histoire-intro.js',
                'js/charger-histoire-textes.js',
                'js/layout-jeu.js',
                'js/moteur-config-actions.js',
            ],
            thresholds: {
                lines: 52,
                functions: 55,
                statements: 50,
                branches: 44,
            },
        },
    },
});
