import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        include: ['tests/**/*.test.mjs'],
        setupFiles: ['tests/setup.mjs'],
        coverage: {
            provider: 'v8',
            include: [
                'js/logique-pure.js',
                'js/progression.js',
                'js/progression-stockage.js',
                'js/progression-records.js',
                'js/progression-histoire.js',
                'js/boss-attaques.js',
                'js/registre-modes.js',
                'js/piece-jeu.js',
                'js/moteur-piece.js',
                'js/achievements.js',
                'js/logique-partie.js',
                'js/logique-partie-verrouillage.js',
                'js/logique-partie-mouvement.js',
                'js/logique-partie-score.js',
                'js/logique-partie-hold.js',
                'js/logique-partie-pose.js',
                'js/planificateur-raf.js',
                'js/oracle-jeu.js',
                'js/oracle-placement.js',
                'js/coop-logique.js',
                'js/coop-logique-piece.js',
                'js/coop-logique-mouvement.js',
                'js/archi-logique.js',
                'js/score-partie.js',
                'js/bus-jeu.js',
                'js/boucle-jeu.js',
                'js/expressions-cutscene.js',
                'js/effets-partie.js',
                'js/charger-ecrans.js',
                'js/meteo.js',
                'js/timer-niveau.js',
                'js/histoire-narratif.js',
                'js/vivant.js',
                'js/vivant-strategies.js',
                'js/actions-piece-communes.js',
                'js/mecaniques-histoire.js',
                'js/mecaniques-histoire-queries.js',
                'js/mecaniques-histoire-rouille.js',
                'js/mecaniques-histoire-eclipse.js',
                'js/mecaniques-histoire-vide.js',
                'js/mecaniques-histoire-trame.js',
                'js/mecaniques-histoire-miroir.js',
                'js/rendu-fond-biome-donnees.js',
                'js/rendu-fond-biome-particules.js',
                'js/histoire-map-panneau-details.js',
                'js/histoire-map-interactions.js',
                'js/conditions-secrets.js',
                'js/histoire-etat.js',
                'js/histoire-manager.js',
                'js/histoire-manager-completion.js',
                'js/boss-jeu.js',
                'js/rendu-robo.js',
                'js/mascotte-robo.js',
                'js/portraits-cutscene.js',
                'js/partie-fin.js',
                'js/histoire-intro.js',
                'js/charger-histoire-textes.js',
                'js/layout-jeu.js',
                'js/layout-calcul.js',
                'js/buffer-input-jeu.js',
                'js/game-feel-jeu.js',
                'js/coop-game-feel.js',
                'js/reactions-boss-portrait.js',
                'js/coop-lignes-score.js',
                'js/haptique.js',
                'js/histoire-narratif-scenes.js',
                'js/rendu-fx.js',
                'js/gestionnaire-difficulte.js',
                'js/prechargement-medias.js',
                'js/moteur-config-actions.js',
                'js/boss-combat.js',
                'js/mode-histoire.js',
                'js/rendu-plateau-cache.js',
                'js/navigation-ecrans.js',
                'js/histoire-cutscene-fonds-animes.js',
                'js/histoire-cutscene-fonds-scenes.js',
                'js/tutoriel-contenus.js',
                'js/scenes-cutscene.js',
                'js/safe-area.js',
                'js/orientation-jeu.js',
                'js/histoire-manager-post-monde.js',
                'js/rendu-plateau-pieces.js',
                'js/portraits-cutscene-etat.js',
                'js/histoire-map-briefings-boss.js',
                'js/histoire-map-fond-donnees.js',
                'js/portraits-precache.js',
                'js/chargement-watchdog.js',
                'js/infobulles-contexte.js',
            ],
            thresholds: {
                lines: 54,
                functions: 56,
                statements: 52,
                branches: 46,
            },
        },
    },
});
