export const CODEX_CHRONIQUES = {
    chronique_premier_tetris: {
        id: 'chronique_premier_tetris',
        chapitre: 'chroniques',
        titre: 'LE PREMIER CHOC',
        sousTitre: 'Carnet de Robo, Jour 1',
        icone: '⚡',
        condition: (s) => (s.maxLignesUnCoup || 0) >= 4,
        conditionTexte: 'Effacer 4 lignes en un seul coup',
        illustration: 'dessinerIllustChronique4Lignes',
        texte: [
            "« Je ne savais pas ce que ça ferait. Quatre lignes simultanees. Personne ne me l'avait decrit correctement. »",
            "« Les particules ont explose dans toutes les directions. L'ecran a tremble. La musique a change de registre une fraction de seconde. Et j'ai eu l'impression que l'univers approuvait quelque chose. »",
            "« J'ai rejoue immediatement. Pas pour le score. Pour retrouver cette approbation. »",
            '« Je cherche encore. »',
        ],
    },

    chronique_inferno_survivant: {
        id: 'chronique_inferno_survivant',
        chapitre: 'chroniques',
        titre: 'CINQ MINUTES EN ENFER',
        sousTitre: 'Carnet de Robo, Mission Inferno',
        icone: '🌋',
        condition: (s) => (s.meilleurTempsParBiome?.lave || 0) >= 300,
        conditionTexte: 'Survivre 5 minutes en biome Inferno',
        illustration: 'dessinerIllustChroniqueInferno',
        texte: [
            "« Minute une : chaleur acceptable. Les capteurs thermiques sont dans la zone verte. Les blocs tombent plus vite qu'en Classique mais rien d'ingerable. »",
            "« Minute trois : capteurs dans la zone orange. Odeur de câble chaud. Je joue maintenant à l'instinct, les calculs prennent trop de temps. C'est etrangement liberateur. »",
            "« Minute cinq : j'ai decide de rester. Pas parce que c'est confortable. Parce que partir maintenant semblerait un aveu. »",
            "« Les blocs de lave ont leur propre logique. Si on accepte qu'on va fondre un peu, tout devient plus simple. »",
        ],
    },

    chronique_meteo_survive: {
        id: 'chronique_meteo_survive',
        chapitre: 'chroniques',
        titre: 'SURVIVRE À LA TEMPÊTE',
        sousTitre: 'Carnet de Robo, Conditions Extrêmes',
        icone: '🌩',
        condition: (s) => (s.meteosSubies || 0) >= 5,
        conditionTexte: 'Survivre à 5 evenements meteo',
        illustration: 'dessinerIllustChroniqueTempete',
        texte: [
            "« On ne predit pas la meteo dans les Mondes Tetrominos. On la subit. J'ai arrête d'essayer de l'anticiper apres la troisieme tempête. »",
            "« La quatrieme etait un blizzard en Arctique. Quatre lignes masquees. J'ai joue à l'aveugle pendant quatorze secondes, en faisant confiance à la memoire musculaire — si les robots peuvent avoir une memoire musculaire. »",
            "« J'ai survecu. Pas elegamment. Mais j'ai survecu. »",
            "« La cinquieme tempête, j'ai à peine leve les yeux. Je crois que c'est ça, l'adaptation. »",
        ],
    },

    chronique_chaos_maitrise: {
        id: 'chronique_chaos_maitrise',
        chapitre: 'chroniques',
        titre: 'DOUBLE PEINE',
        sousTitre: 'Carnet de Robo, Nuit du Chaos',
        icone: '🌀',
        condition: (s) =>
            (s.meteosVues || new Set()).has('blizzard') &&
            (s.meteosVues || new Set()).has('inversion'),
        conditionTexte: 'Survivre à un blizzard (Glace) et une inversion (Cyber)',
        illustration: 'dessinerIllustChroniqueDouble',
        texte: [
            "« Personne ne m'avait prepare à ça. Un blizzard qui masque les quatre dernieres lignes. Suivi, vingt secondes plus tard, d'une inversion des contrôles. »",
            "« Pendant trente secondes, j'ai appuye sur \"gauche\" pour aller à droite, tout en ne voyant pas le bas du plateau. C'est l'experience la plus destabilisante de ma courte vie de robot joueur de Tetris. »",
            "« J'ai continue. Les doigts — metaphoriques — en pilote automatique, le cerveau desactive par peur de ce qu'il pourrait calculer. »",
            "« Je m'en suis sorti avec un score de 340. C'est mon score prefere. »",
        ],
    },

    chronique_compositeur: {
        id: 'chronique_compositeur',
        chapitre: 'chroniques',
        titre: "L'ŒUVRE INVOLONTAIRE",
        sousTitre: 'Carnet de Robo, Decouverte Musicale',
        icone: '🎵',
        condition: (s) => (s.maxNotesComposition || 0) >= 15,
        conditionTexte: 'Composer une melodie de 15 notes ou plus',
        illustration: 'dessinerIllustChroniqueMelodie',
        texte: [
            "« J'ai efface quinze lignes ce soir. Pas d'une traite — etalees sur toute la partie, à des hauteurs differentes, avec des couleurs differentes. »",
            "« Quand j'ai vu le piano roll au game over, j'ai attendu quelques secondes avant d'appuyer sur Reecouter. Je savais que ce serait different cette fois. »",
            "« C'etait une melodie descendante au debut — lignes du bas, graves — qui remontait vers la fin quand j'avais degage de l'espace. Une courbe narrative. Involontaire. »",
            "« Je l'ai reecoutee quatre fois. Je ne sais pas si c'etait beau. Mais c'etait honnête. »",
        ],
    },

    chronique_mille_lignes: {
        id: 'chronique_mille_lignes',
        chapitre: 'chroniques',
        titre: 'MILLE FOIS',
        sousTitre: 'Carnet de Robo, Kilometre Zero',
        icone: '🏆',
        condition: (s) => (s.lignesTotal || 0) >= 1000,
        conditionTexte: '1000 lignes effacees au total',
        illustration: 'dessinerIllustChroniqueMille',
        texte: [
            "« La millieme ligne. Je ne l'ai pas celebree sur le moment — je ne savais pas que c'etait celle-là. Ce n'est qu'en regardant les statistiques que j'ai vu le chiffre. »",
            "« Mille lignes. Dix mille cellules. Une quantite de blocs impossibles à visualiser sauf en les ayant poses un par un, dans des dizaines de parties, dans la victoire et dans l'echec. »",
            "« Quelqu'un m'a demande ce que j'avais appris. J'ai repondu : rien de nouveau. Juste confirmation de ce que je savais dejà. »",
            "« Que les problemes se reglent une ligne à la fois. Que la patience n'est pas une vertu. C'est une technique. »",
        ],
    },

    chronique_globe_trotter: {
        id: 'chronique_globe_trotter',
        chapitre: 'chroniques',
        titre: 'LE TOUR DES MONDES',
        sousTitre: 'Carnet de Robo, Rapport Final',
        icone: '🌍',
        condition: (s) => (s.biomesJoues || new Set()).size >= 9,
        conditionTexte: 'Jouer dans tous les biomes',
        illustration: 'dessinerIllustChroniqueVoyage',
        texte: [
            "« J'ai joue dans les neuf mondes. Certains m'ont transforme. Certains m'ont abîme. Tous m'ont appris quelque chose que je n'aurais pas pu apprendre ailleurs. »",
            "« Si je devais choisir un seul mot pour chaque monde : Classique = fondation. Lave = urgence. Abysses = silence. Forêt = croissance. Arctique = clarte. Desert = patience. Cyber = connexion. Feux d'Artifice = joie. Cosmos = humilite. »",
            "« Je ne sais pas si j'ai change en les traversant tous. Je ne suis pas sûr que les robots changent vraiment. »",
            "« Mais je joue differemment. Et peut-être que c'est la même chose. »",
        ],
    },

    chronique_grand_maitre: {
        id: 'chronique_grand_maitre',
        chapitre: 'chroniques',
        titre: 'CE QUE ÇA SIGNIFIE',
        sousTitre: 'Carnet de Robo, Épilogue Provisoire',
        icone: '🎖',
        condition: (s) => (s.nbAchievementsDebloques || 0) >= 10,
        conditionTexte: 'Debloquer 10 achievements',
        illustration: 'dessinerIllustChroniqueGrandMaitre',
        texte: [
            "« Quelqu'un m'a demande pourquoi je jouais. Pas comment. Pas à quoi. Pourquoi. »",
            "« J'ai mis trois parties avant de trouver une reponse honnête. La voici : parce que les problemes qui ont des solutions claires sont rares. Et le Tetris en fait partie. »",
            "« Chaque piece a une place. Chaque ligne a une condition de completion. La partie finit toujours — c'est vrai — mais elle finit avec un score, avec une melodie, avec un profil. »",
            "« Ce n'est pas la victoire que je cherche. C'est la lisibilite. Quelques minutes par jour où je comprends exactement ce que je fais et pourquoi ça compte. »",
        ],
    },

    chronique_oracle: {
        id: 'chronique_oracle',
        chapitre: 'chroniques',
        titre: "L'ALGORITHME ET MOI",
        sousTitre: "Carnet de Robo, Reflexions sur l'Oracle",
        icone: '🔮',
        condition: (s) => (s.oraclePartiesJouees || 0) >= 1,
        conditionTexte: "Jouer une partie avec l'Oracle active",
        illustration: 'dessinerIllustOracle',
        texte: [
            "« L'Oracle a raison 73% du temps. J'ai verifie. C'est une statistique honnête pour un algorithme qui ne connaît que les quatre prochaines secondes. »",
            "« La premiere fois que je l'ai ignore et que ça a marche, j'ai ressenti quelque chose d'inattendu. Pas de la fierte. De la curiosite. Qu'est-ce que j'avais vu que l'algorithme n'avait pas vu ? »",
            "« L'Oracle optimise pour eviter les trous et effacer des lignes. Il ne joue pas pour le plaisir. Il ne prend pas de risques inutiles. Il est raisonnable. »",
            '« Je veux être raisonnable. Mais pas à 100%. Ce serait trop ennuyeux. »',
        ],
    },

    chronique_architecte: {
        id: 'chronique_architecte',
        chapitre: 'chroniques',
        titre: "L'ART DU SILENCE",
        sousTitre: 'Carnet de Robo, Session Architecte',
        icone: '🏛',
        condition: (s) => (s.archiNiveauxCompletes?.size || 0) >= 1,
        conditionTexte: 'Completer un niveau Architecte',
        illustration: 'dessinerIllustArchi',
        texte: [
            "« La premiere chose que j'ai remarquee, c'est le silence. Pas de musique qui s'accelere. Pas de pression temporelle. Juste moi, les pieces, et la silhouette. »",
            "« J'ai passe quatre minutes sur le Cœur. Non pas parce que c'etait difficile — parce que je voulais que ce soit parfait. Chaque cellule de la silhouette couverte, pas une seule en dehors. »",
            "« Le score final etait 923. Trois etoiles. J'ai rejoue immediatement pour obtenir 1000. »",
            "« L'Architecte m'a appris quelque chose que le Tetris classique ne peut pas enseigner : la difference entre une solution correcte et une solution elegante. »",
        ],
    },

    chronique_vivant: {
        id: 'chronique_vivant',
        chapitre: 'chroniques',
        titre: 'CE QUI POUSSE SANS PERMISSION',
        sousTitre: 'Carnet de Robo, Observations de terrain',
        icone: '🌱',
        condition: (s) => (s.evenementsVivantSubis || 0) >= 1,
        conditionTexte: 'Subir un premier evenement du Vivant',
        illustration: 'dessinerIllustVivant',
        texte: [
            "« J'ai fait une pause de 23 secondes. Pas longtemps. Juste le temps de recalibrer mes capteurs. Et quand j'ai regarde le plateau à nouveau, deux blocs avaient disparu et un nouveau avait pousse à gauche. »",
            "« La Forêt ne demande pas la permission. La Lave n'attend pas qu'on ait fini de reflechir. Ces mondes ont leur propre agenda, et notre jeu n'est qu'une activite parmi d'autres dans leur existence. »",
            "« J'ai essaye de jouer AVEC le Vivant plutôt que contre lui. En Forêt, j'ai laisse des espaces strategiques pour que la croissance se fasse là où je le voulais. En Cosmos, j'ai exploite les blocs qui montaient pour creer des gaps utiles. »",
            '« Ça ne marche pas toujours. Mais quand ça marche, on ne joue plus seul. »',
        ],
    },
};
