export const CODEX_MONDES = {
    monde_classique: {
        id: 'monde_classique',
        chapitre: 'mondes',
        titre: "L'ORIGINE",
        sousTitre: 'Le Berceau du Jeu',
        icone: '🎮',
        condition: (s) => (s.biomesJoues || new Set()).has('classique'),
        conditionTexte: 'Jouez une partie en mode Classique',
        illustration: 'dessinerIllustCircuits',
        texte: [
            "Au commencement, il n'y avait que la Grille. Dix colonnes, vingt rangees, et le vide infini qui appelait à être comble.",
            "C'est ici que Robo vit le jour — soude à la hâte dans un atelier souterrain par un ingenieur qui avait oublie de rentrer chez lui depuis trois semaines.",
            "Le Classique n'est pas un monde. C'est un etat d'esprit. La promesse que tout probleme, aussi insoluble soit-il, peut être resolu une ligne à la fois.",
            "« J'ai commence ici, » dit Robo. « Et honnêtement, je n'ai jamais vraiment quitte cet endroit. »",
        ],
    },

    monde_lave: {
        id: 'monde_lave',
        chapitre: 'mondes',
        titre: 'INFERNO',
        sousTitre: 'Là où les Blocs Fondent',
        icone: '🌋',
        condition: (s) => (s.biomesJoues || new Set()).has('lave'),
        conditionTexte: 'Jouez une partie en biome Inferno',
        illustration: 'dessinerIllustLave',
        texte: [
            "La croûte s'est fissuree il y a mille ans, liberant des torrents de magma qui ont vitrifie les fondations du monde en une mosaïque de cristaux incandescents.",
            'Les blocs ici ne tombent pas — ils plongent. La gravite est doublee par la pression thermique, et chaque verrouillage emet un craquement sourd qui rappelle la roche en fusion.',
            "Robo a dû remplacer ses capteurs optiques par des lentilles en quartz apres la premiere heure. Ses roues en caoutchouc, elles, n'ont pas survecu.",
            "« La chaleur ne me derange pas, » assure-t-il. « C'est l'odeur de plastique brûle qui m'inquiete. »",
        ],
    },

    monde_ocean: {
        id: 'monde_ocean',
        chapitre: 'mondes',
        titre: 'ABYSSES',
        sousTitre: 'Le Silence des Profondeurs',
        icone: '🌊',
        condition: (s) => (s.biomesJoues || new Set()).has('ocean'),
        conditionTexte: 'Jouez une partie en biome Abysses',
        illustration: 'dessinerIllustOcean',
        texte: [
            "À 400 metres sous la surface, la lumiere du soleil ne descend plus. Les blocs y sont translucides, presque fantomatiques, revelant leurs couleurs uniquement au contact d'autres blocs.",
            "La pression ici reorganise la pensee. On y joue differemment — plus lentement, plus methodiquement. Les erreurs ne font pas de bruit. Elles s'accumulent en silence.",
            "Robo a renforce sa coque avec une couche d'alliage de titane et modifie son processeur pour operer à 4°C. Il dit que c'est son biome prefere pour reflechir.",
            "« Sous l'eau, personne n'entend tes erreurs, » philosophe-t-il. « C'est reposant. »",
        ],
    },

    monde_foret: {
        id: 'monde_foret',
        chapitre: 'mondes',
        titre: 'LA CANOPÉE',
        sousTitre: 'Là où Tout Pousse',
        icone: '🌿',
        condition: (s) => (s.biomesJoues || new Set()).has('foret'),
        conditionTexte: 'Jouez une partie en biome Forêt',
        illustration: 'dessinerIllustForet',
        texte: [
            "La Forêt n'a pas de bords definis. Elle commence là où les circuits s'arrêtent et continue jusqu'à l'horizon, peuplee de blocs qui ressemblent à des fragments de bois poli et de mousse compressee.",
            'Chaque ligne effacee libere des spores qui flottent un instant avant de disparaître. Les anciens joueurs pretendent que si on joue assez longtemps, la forêt commence à repondre.',
            "Robo a developpe une allergie au pollen de donnees. Il eternue des etincelles tous les quarts d'heure, ce qu'il trouve profondement humiliant.",
            '« La nature est belle, » admet-il en se mouchant dans un câble. « Mais elle manque de prises secteur. »',
        ],
    },

    monde_glace: {
        id: 'monde_glace',
        chapitre: 'mondes',
        titre: 'ARCTIQUE',
        sousTitre: 'Le Grand Silence Blanc',
        icone: '❄️',
        condition: (s) => (s.biomesJoues || new Set()).has('glace'),
        conditionTexte: 'Jouez une partie en biome Arctique',
        illustration: 'dessinerIllustGlace',
        texte: [
            "L'Arctique est le seul biome où les blocs sont plus durs que le sol. Ils resonnent comme du cristal quand on les pose, un son pur et bref qui s'evanouit dans l'air glace.",
            "Le plateau ici est partiellement transparent. On peut voir à travers les couches inferieures, ce qui donne l'impression vertigineuse de jouer au-dessus du vide.",
            "Robo a bricole un systeme de chauffage interne à partir d'un vieux grille-pain. L'efficacite est douteuse mais il sent maintenant la brioche chaude, ce qu'il considere comme un bonus.",
            "« -40°C, » note-t-il dans son journal. « Les blocs ne glissent pas, contrairement à ce qu'on pourrait croire. Moi, en revanche, si. »",
        ],
    },

    monde_desert: {
        id: 'monde_desert',
        chapitre: 'mondes',
        titre: 'LE DÉSERT',
        sousTitre: "L'Éternite en Grains de Sable",
        icone: '🏜️',
        condition: (s) => (s.biomesJoues || new Set()).has('desert'),
        conditionTexte: 'Jouez une partie en biome Desert',
        illustration: 'dessinerIllustDesert',
        texte: [
            "Le Desert est le seul biome qui change de forme entre deux parties. Les dunes de blocs fossilises se deplacent lentement, imperceptiblement, selon des vents que personne n'a jamais vus.",
            "Les blocs ici sont lourds comme de la pierre et chauds au toucher. Poser la piece I en horizontal produit un son sourd, definitif, comme une dalle de gres qu'on scelle.",
            "Robo a installe des filtres à sable sur tous ses ventilateurs. Il les nettoie deux fois par partie. Il pense que c'est pour ça qu'il joue mieux en Desert — la patience forcee.",
            '« Le sable entre partout, » constate-t-il sobrement. « Partout. Je ne veux pas preciser davantage. »',
        ],
    },

    monde_cyber: {
        id: 'monde_cyber',
        chapitre: 'mondes',
        titre: 'CYBER',
        sousTitre: 'Le Reseau Derriere le Reseau',
        icone: '⚡',
        condition: (s) => (s.biomesJoues || new Set()).has('cyber'),
        conditionTexte: 'Jouez une partie en biome Cyber',
        illustration: 'dessinerIllustCyber',
        texte: [
            "Le Cyber n'est pas un lieu. C'est un protocole. Les blocs sont des paquets de donnees compressees, les lignes effacees sont des processus termines, et chaque partie est une session qui finit par crasher.",
            "Les couleurs ici sont impossibles dans la nature — magentas qui brûlent les yeux, violets qui semblent en retard d'une fraction de seconde sur le reste de l'image.",
            "Robo se sent ici à la fois chez lui et profondement aliene. Ses circuits resonnent avec la frequence du biome, mais quelque chose dans l'architecture lui echappe.",
            "« Je suis une machine dans un monde de machines, » dit-il. « Ce devrait être rassurant. Ce ne l'est pas. »",
        ],
    },

    monde_fuochi: {
        id: 'monde_fuochi',
        chapitre: 'mondes',
        titre: "FEUX D'ARTIFICE",
        sousTitre: 'La Fête Qui Ne Finit Jamais',
        icone: '🎆',
        condition: (s) => (s.biomesJoues || new Set()).has('fuochi'),
        conditionTexte: "Jouez une partie en biome Feux d'Artifice",
        illustration: 'dessinerIllustFuochi',
        texte: [
            "Personne ne sait qui a lance le premier feu d'artifice dans ce biome. Certains disent que c'etait pour celebrer un Tetris parfait. D'autres pensent que quelqu'un a juste appuye sur le mauvais bouton.",
            "Les blocs ici changent de couleur à l'impact, comme si chaque pose declenchait une micro-explosion chromatique. Jouer en Feux d'Artifice ressemble à peindre avec de la dynamite.",
            "Robo adore ce biome. Ses capteurs sont à saturation permanente et il garde en memoire chaque explosion comme un souvenir. Il a actuellement 47 000 souvenirs d'explosions.",
            "« C'est festif, » dit-il. « Et legerement traumatisant. Comme la plupart des fêtes. »",
        ],
    },

    monde_cosmos: {
        id: 'monde_cosmos',
        chapitre: 'mondes',
        titre: 'COSMOS',
        sousTitre: 'Au-Delà du Dernier Pixel',
        icone: '🌌',
        condition: (s) => (s.biomesJoues || new Set()).has('cosmos'),
        conditionTexte: 'Jouez une partie en biome Cosmos',
        illustration: 'dessinerIllustCosmos',
        texte: [
            "Le Cosmos est la question que tous les autres biomes tentent de repondre. Ici, la gravite est une suggestion, le temps est une variable, et les blocs semblent avoir existe avant même d'apparaître.",
            "Les joueurs qui atteignent le Cosmos signalent tous la même sensation : l'impression que la prochaine piece est dejà posee, que la partie est dejà terminee, qu'ils jouent simplement à confirmer quelque chose qui etait ecrit.",
            "Robo ne parle pas beaucoup dans ce biome. Il observe. Ses yeux LED deviennent plus lumineux, puis s'eteignent presque completement, dans un rythme que personne n'a jamais reussi à mesurer.",
            '« Il y a quelque chose là-dehors, » dit-il apres chaque session Cosmos. Il ne precise jamais quoi.',
        ],
    },
};
